import { Edit } from "lucide-react";
import { UserData } from "./types";

export const userData : UserData[]= [
    {
      userId: "abc@gmail.com",
      userName: "jom",
      empCode: "1234",
      department: ["It"],
      plant: ["Unit1-1100"],
       role: ['User'],
        hod:  "abcdef@gmail.com",
      isActive: false
    },
    {
      userId: "abc@gmail.com",
      userName: "jom",
      empCode: "1234",
      department: ["It"],
      plant: ["Unit1-1100"],
       role: ['User'],
        hod:  "abcdef@gmail.com",
      isActive: true
    }, {
      userId: "abc@gmail.com",
      userName: "jom",
      empCode: "1234",
      department: ["It"],
      plant: ["Unit1-1100"],
       role: ['User'],
        hod:  "abcdef@gmail.com",
      isActive: true
    }, {
      userId: "abc@gmail.com",
      userName: "jom",
      empCode: "1234",
      department: ["It"],
      plant: ["Unit1-1100"],
       role: ['User'],
        hod:  "abcdef@gmail.com",
      isActive: true
    }, {
      userId: "abc@gmail.com",
      userName: "jom",
      empCode: "1234",
      department: ["It"],
      plant: ["Unit1-1100"],
       role: ['User'],
        hod:  "abcdef@gmail.com",
      isActive: true
    }, {
      userId: "abc@gmail.com",
      userName: "jom",
      empCode: "1234",
      department: ["It"],
      plant: ["Unit1-1100"],
       role: ['User'],
        hod:  "abcdef@gmail.com",
      isActive: true
    }, {
      userId: "abc@gmail.com",
      userName: "jom",
      empCode: "1234",
      department: ["It"],
      plant: ["Unit1-1100"],
       role: ['User'],
        hod:  "abcdef@gmail.com",
      isActive: true
    }, {
      userId: "abc@gmail.com",
      userName: "jom",
      empCode: "1234",
      department: ["It"],
      plant: ["Unit1-1100"],
       role: ['User'],
        hod:  "abcdef@gmail.com",
      isActive: true
    }, {
      userId: "abc@gmail.com",
      userName: "jom",
      empCode: "1234",
      department: ["It"],
      plant: ["Unit1-1100"],
       role: ['User'],
        hod:  "abcdef@gmail.com",
      isActive: true
    }, {
      userId: "abc@gmail.com",
      userName: "jom",
      empCode: "1234",
      department: ["It"],
      plant: ["Unit1-1100"],
       role: ['User'],
        hod:  "abcdef@gmail.com",
      isActive: true
    }, {
      userId: "abc@gmail.com",
      userName: "jom",
      empCode: "1234",
      department: ["It"],
      plant: ["Unit1-1100"],
       role: ['User'],
        hod:  "abcdef@gmail.com",
      isActive: true
    }, {
      userId: "abc@gmail.com",
      userName: "jom",
      empCode: "1234",
      department: ["It"],
      plant: ["Unit1-1100"],
       role: ['User'],
        hod:  "abcdef@gmail.com",
      isActive: true
    }, {
      userId: "abc@gmail.com",
      userName: "jom",
      empCode: "1234",
      department: ["It"],
      plant: ["Unit1-1100"],
       role: ['User'],
        hod:  "abcdef@gmail.com",
      isActive: true
    }, {
      userId: "abc@gmail.com",
      userName: "jom",
      empCode: "1234",
      department: ["It"],
      plant: ["Unit1-1100"],
       role: ['User'],
        hod:  "abcdef@gmail.com",
      isActive: true
    }, {
      userId: "abc@gmail.com",
      userName: "jom",
      empCode: "1234",
      department: ["It"],
      plant: ["Unit1-1100"],
       role: ['User'],
        hod:  "abcdef@gmail.com",
      isActive: true
    }, {
      userId: "abc@gmail.com",
      userName: "jom",
      empCode: "1234",
      department: ["It"],
      plant: ["Unit1-1100"],
       role: ['User'],
        hod:  "abcdef@gmail.com",
      isActive: true
    },
];