import { Edit } from "lucide-react";
import { UserData } from "./types";

export const userData : UserData[]= [
    {
      userId: "abc@gmail.com",
      userName: "jom",
      empCode: "1234",
      department: ["It"],
      plant: ["Unit1-1100"],
      hod:  "abcdef@gmail.com",
    },
     {
      userId: "abc@gmail.com",
      userName: "jom",
      empCode: "1234",
      department: ["It"],
      plant: ["Unit1-1100"],
      hod:  "abcdef@gmail.com",
    },
     {
      userId: "abc@gmail.com",
      userName: "jom",
      empCode: "1234",
      department: ["It"],
      plant: ["Unit1-1100"],
      hod:  "abcdef@gmail.com",
    },
    {
      userId: "abc@gmail.com",
      userName: "jom",
      empCode: "1234",
      department: ["It"],
      plant: ["Unit1-1100"],
      hod:  "abcdef@gmail.com",
    },
     {
      userId: "abc@gmail.com",
      userName: "jom",
      empCode: "1234",
      department: ["It"],
      plant: ["Unit1-1100"],
      hod:  "abcdef@gmail.com",
    },
     {
      userId: "abc@gmail.com",
      userName: "jom",
      empCode: "1234",
      department: ["It"],
      plant: ["Unit1-1100"],
      hod:  "abcdef@gmail.com",
    },
    {
      userId: "abc@gmail.com",
      userName: "jom",
      empCode: "1234",
      department: ["It"],
      plant: ["Unit1-1100"],
      hod:  "abcdef@gmail.com",
    },
     {
      userId: "abc@gmail.com",
      userName: "jom",
      empCode: "1234",
      department: ["It"],
      plant: ["Unit1-1100"],
      hod:  "abcdef@gmail.com",
    },
     {
      userId: "abc@gmail.com",
      userName: "jom",
      empCode: "1234",
      department: ["It"],
      plant: ["Unit1-1100"],
      hod:  "abcdef@gmail.com",
    },
    {
      userId: "abc@gmail.com",
      userName: "jom",
      empCode: "1234",
      department: ["It"],
      plant: ["Unit1-1100"],
      hod:  "abcdef@gmail.com",
    },
     {
      userId: "abc@gmail.com",
      userName: "jom",
      empCode: "1234",
      department: ["It"],
      plant: ["Unit1-1100"],
      hod:  "abcdef@gmail.com",
    },
     {
      userId: "abc@gmail.com",
      userName: "jom",
      empCode: "1234",
      department: ["It"],
      plant: ["Unit1-1100"],
      hod:  "abcdef@gmail.com",
    },
    {
      userId: "abc@gmail.com",
      userName: "jom",
      empCode: "1234",
      department: ["It"],
      plant: ["Unit1-1100"],
      hod:  "abcdef@gmail.com",
    },
     {
      userId: "abc@gmail.com",
      userName: "jom",
      empCode: "1234",
      department: ["It"],
      plant: ["Unit1-1100"],
      hod:  "abcdef@gmail.com",
    },
    {
      userId: "abc@gmail.com",
      userName: "jom",
      empCode: "1234",
      department: ["It"],
      plant: ["Unit1-1100"],
      hod:  "abcdef@gmail.com",
    },
     {
      userId: "abc@gmail.com",
      userName: "jom",
      empCode: "1234",
      department: ["It"],
      plant: ["Unit1-1100"],
      hod:  "abcdef@gmail.com",
    },
    {
      userId: "abc@gmail.com",
      userName: "jom",
      empCode: "1234",
      department: ["It"],
      plant: ["Unit1-1100"],
      hod:  "abcdef@gmail.com",
    },
     {
      userId: "abc@gmail.com",
      userName: "jom",
      empCode: "1234",
      department: ["It"],
      plant: ["Unit1-1100"],
      hod:  "abcdef@gmail.com",
    }
];