import { MRRequest } from "./types";

export const materialRequest: MRRequest[] = [
  {
    material: "60003097",
    materialType: "ERSA",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: 'SM-PU-ELBOW-1/8"X8MM',
  },
  {
    material: "60003099",
    materialType: "ERSA",
    materialGroup: "SM",
    buom: "NOS",
    status: "pending",
    materialDescription: "SM-SS-ALLEN-BOLT-5X12MM",
  },
  {
    material: "60003101",
    materialType: "ERSA",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-AIR-FILTER-21702911-500KVA-DG",
  },
  {
    material: "60003117",
    materialType: "ERSA",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: 'SM-VALVE-SOLENOID-5/2"X1/4"-24VDC-MAKE',
  },
  {
    material: "60003119",
    materialType: "ERSA",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "EE-TUBE-LIGH-T5-FITTING-14W-PHILIPS",
  },
  {
    material: "60003127",
    materialType: "ERSA",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-PVC-MOTOR-COOLING-FAN-15/25HP",
  },
  {
    material: "60003141",
    materialType: "ERSA",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-HT-HEX-BOLT-20X60MM",
  },
  {
    material: "60003146",
    materialType: "ERSA",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-HT-HEX-BOLT-12X35MM",
  },
  {
    material: "60003152",
    materialType: "ERSA",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: 'SM-WOOD-CUTTING-BLADE-4"',
  },
  {
    material: "60003178",
    materialType: "ERSA",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-BEARING-6005-ZZ",
  },
  {
    material: "60003224",
    materialType: "ERSA",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-EMERY-PAPER-100",
  },
  {
    material: "60003276",
    materialType: "ERSA",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: 'SM-NEOPRENE-RUBBER-BELLOW-COUPLING-6"',
  },
  {
    material: "60003279",
    materialType: "ERSA",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-MS-SCREW-8X38MM",
  },
  {
    material: "60003288",
    materialType: "ERSA",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: 'SM-MS-REDUCER-�"X3/4"',
  },
  {
    material: "60003306",
    materialType: "ERSA",
    materialGroup: "SM",
    buom: "M",
    status: "approved",
    materialDescription: "SM-PVC-PIPE-FLEXIBLE-20MM",
  },
  {
    material: "60003314",
    materialType: "ERSA",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-JOINT-MH02016650",
  },
  {
    material: "60003336",
    materialType: "ERSA",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-CIRCLIP-INTERNAL-90MM",
  },
  {
    material: "60003347",
    materialType: "ERSA",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-T-ROLL-BEARING-MH-55300006",
  },
  {
    material: "60003350",
    materialType: "ERSA",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-REV-HORN-MH-59073004",
  },
  {
    material: "60003355",
    materialType: "ERSA",
    materialGroup: "SM",
    buom: "M",
    status: "approved",
    materialDescription: "SM-PVC-PIPE-FLEXIBLE-25MM",
  },
  {
    material: "60003359",
    materialType: "ERSA",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-STRIP-REVERSE-HORN-MH02364890",
  },
  {
    material: "60003360",
    materialType: "ERSA",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-SWITCH-MH02292630",
  },
  {
    material: "60003365",
    materialType: "ERSA",
    materialGroup: "SM",
    buom: "M",
    status: "approved",
    materialDescription: "SM-RUBBER-CORD-6MM",
  },
  {
    material: "60003385",
    materialType: "ERSA",
    materialGroup: "SM",
    buom: "L",
    status: "approved",
    materialDescription: "SM-PAINT-APCOLITE-ENAMEL-PHIROZA-ASIAN",
  },
  {
    material: "60003410",
    materialType: "ERSA",
    materialGroup: "SM",
    buom: "M",
    status: "approved",
    materialDescription: "SM-RUBBER-CORD-3.5MM",
  },
  {
    material: "60003414",
    materialType: "ERSA",
    materialGroup: "SM",
    buom: "SET",
    status: "approved",
    materialDescription: "SM-CI-BRACKET-��X18�",
  },
  {
    material: "60003421",
    materialType: "ERSA",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-NBR-OIL-SEAL-22X42X10MM",
  },
  {
    material: "60003426",
    materialType: "ERSA",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-BREAK-LINER-100X1000X8MM",
  },
  {
    material: "60003435",
    materialType: "ERSA",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: 'SM-COUPLING-BRASS-WITH-UNION-&-BUSH-1/4"',
  },
  {
    material: "60003443",
    materialType: "ERSA",
    materialGroup: "SM",
    buom: "M",
    status: "approved",
    materialDescription: "SM-MS-PIPE-10�",
  },
  {
    material: "60003445",
    materialType: "ERSA",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-GI-COUPLING-6�",
  },
  {
    material: "60003463",
    materialType: "ERSA",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-GUN-AIR-WG3020",
  },
  {
    material: "60003465",
    materialType: "ERSA",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-HSS-TAPE-SET-1/4MM",
  },
  {
    material: "60003474",
    materialType: "ERSA",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: 'SM-MS-HYDRAULIC-HEX-NIPPLE-3/8"X1/2"',
  },
  {
    material: "60003487",
    materialType: "ERSA",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-COPPER-LUGSPIN-2.5MM",
  },
  {
    material: "60003506",
    materialType: "ERSA",
    materialGroup: "SM",
    buom: "PAC",
    status: "approved",
    materialDescription: "SM-SS316-WELDING-ROD-3.15",
  },
  {
    material: "60003507",
    materialType: "ERSA",
    materialGroup: "SM",
    buom: "L",
    status: "approved",
    materialDescription: "SM-PAINT-APCOLITE-RED-PO-0518",
  },
  {
    material: "60003512",
    materialType: "ERSA",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: 'SM-PVC-CONNECTOR-1"X1"',
  },
  {
    material: "60003520",
    materialType: "ERSA",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-SILICON-ANABOND-RTV",
  },
  {
    material: "60003524",
    materialType: "ERSA",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-FILE-HALF-ROUND-12''",
  },
  {
    material: "60003537",
    materialType: "ERSA",
    materialGroup: "SM",
    buom: "L",
    status: "approved",
    materialDescription: "SM-PAINT-APCOLITE-GREY-AD",
  },
  {
    material: "60003542",
    materialType: "ERSA",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: 'SM-PU-TROLLEY-WHEEL-3" MOVABLE-BRACKET',
  },
  {
    material: "60003555",
    materialType: "ERSA",
    materialGroup: "SM",
    buom: "KG",
    status: "approved",
    materialDescription: "SM-GI-PATTI-25X3MM",
  },
  {
    material: "60003600",
    materialType: "ERSA",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-HYDRAULIC-SEAL-KIT-63X510MM",
  },
  {
    material: "60003626",
    materialType: "ERSA",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-INSTALL-TILT-LOCK-VALVE-MH-02049427",
  },
  {
    material: "60003634",
    materialType: "ERSA",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-N8-SHAFT-30X510-WITH-HARD-CHROME",
  },
  {
    material: "60003636",
    materialType: "ERSA",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-SS-SCREW-8X32MM",
  },
  {
    material: "60003650",
    materialType: "ERSA",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-LOCK-NUT-M10",
  },
  {
    material: "60003659",
    materialType: "ERSA",
    materialGroup: "SM",
    buom: "M",
    status: "approved",
    materialDescription: "SM-NYLON-PIPE-4MM",
  },
  {
    material: "60003668",
    materialType: "ERSA",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: 'SM-BRASS-VALVE-BALL-1/4"',
  },
  {
    material: "60003670",
    materialType: "ERSA",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: 'SM-MS-NIPPLE-1/4"-C-CLASS',
  },
  {
    material: "60003688",
    materialType: "ERSA",
    materialGroup: "SM",
    buom: "L",
    status: "approved",
    materialDescription: "SM-PAINT-WATER-PRIMER",
  },
  {
    material: "60003690",
    materialType: "ERSA",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-VACCUM-PAD-300MM",
  },
  {
    material: "60003710",
    materialType: "ERSA",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: 'SM-MS-COUPLING-1/4"',
  },
  {
    material: "60003711",
    materialType: "ERSA",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: 'SM-MS-COUPLING-3/8"',
  },
  {
    material: "60003720",
    materialType: "ERSA",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-NEOPERENE-OIL-SEAL-70X90X13",
  },
  {
    material: "60003726",
    materialType: "ERSA",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: 'SM-BRASS-HEX-NIPPLE-3/8"',
  },
  {
    material: "60003727",
    materialType: "ERSA",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: 'SM-BRASS-VALVE-BALL-3/8"',
  },
  {
    material: "60003730",
    materialType: "ERSA",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-MS-CIRCLIP-EXTERNAL-18MM",
  },
  {
    material: "60003755",
    materialType: "ERSA",
    materialGroup: "SM",
    buom: "M",
    status: "approved",
    materialDescription: 'SM-PVC-PIPE-BRAIDED-1"',
  },
  {
    material: "60003767",
    materialType: "ERSA",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: 'SM-BRASS-BIB-COCK-LOCKING-1/2"',
  },
  {
    material: "60003784",
    materialType: "ERSA",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-PUMP-AIR-COOLER",
  },
  {
    material: "60003794",
    materialType: "ERSA",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-SS-SCREW-6X25MM",
  },
  {
    material: "60003799",
    materialType: "ERSA",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: 'SM-MS-CHAIN-SPROCKET-DUPLEX-1"-13TEETH',
  },
  {
    material: "60003806",
    materialType: "ERSA",
    materialGroup: "SM",
    buom: "KG",
    status: "approved",
    materialDescription: "SM-GI-SHEET-1MM",
  },
  {
    material: "60003810",
    materialType: "ERSA",
    materialGroup: "SM",
    buom: "M",
    status: "approved",
    materialDescription: "SM-SILICON-CORD-5MM-RED",
  },
  {
    material: "60003815",
    materialType: "ERSA",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: 'SM-HYDRAULIC-PIPE-3/8"X950MM-WITH-FITTIN',
  },
  {
    material: "60003823",
    materialType: "ERSA",
    materialGroup: "SM",
    buom: "KG",
    status: "approved",
    materialDescription: "SM-MS-BOX-PIPE-100X100X6MM",
  },
  {
    material: "60003849",
    materialType: "ERSA",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-CARBIDE-DRILL-5MM",
  },
  {
    material: "60003859",
    materialType: "ERSA",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-PU-UNION-8X8MM",
  },
  {
    material: "60003860",
    materialType: "ERSA",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: 'SM-SS-VALVE-BALL-1�"',
  },
  {
    material: "60003861",
    materialType: "ERSA",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-ALLEN-BOLT-20X90MM",
  },
  {
    material: "60003866",
    materialType: "ERSA",
    materialGroup: "SM",
    buom: "KG",
    status: "approved",
    materialDescription: "SM-EN9-BRIGHT-ROUND-BAR-50MM",
  },
  {
    material: "60003867",
    materialType: "ERSA",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: 'SM-TROLLY-WHEEL-12"-WITH-BEARING',
  },
  {
    material: "60003924",
    materialType: "ERSA",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: 'SM-BEARING-PULLER-10"-3LEG',
  },
  {
    material: "60003945",
    materialType: "ERSA",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-MS-CLUTCH-PLATE-250X75MM",
  },
  {
    material: "60003954",
    materialType: "ERSA",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-ALU-LUGS-RING-25SQMM",
  },
  {
    material: "60003957",
    materialType: "ERSA",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-PEDAL-MH02420594",
  },
  {
    material: "60003962",
    materialType: "ERSA",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-HYDRAULIC-SEAL-KIT-80MM",
  },
  {
    material: "60003993",
    materialType: "ERSA",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-HSS-DRILL-BIT-TAPER-SHUNK-18MM-IT",
  },
  {
    material: "60003998",
    materialType: "ERSA",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: 'SM-DAIMOND-CUP-WHEEL-4"',
  },
  {
    material: "60004001",
    materialType: "ERSA",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "EE-CONTACTOR-POWER-LC1F185,3P-185A",
  },
  {
    material: "60004019",
    materialType: "ERSA",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "EE-LAMP-LED-0.5W",
  },
  {
    material: "60004023",
    materialType: "ERSA",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "EE-PVC-CASSING-PATTY-25X32",
  },
  {
    material: "60004040",
    materialType: "ERSA",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-VALVE-RELFE-MTC-02W",
  },
  {
    material: "60004042",
    materialType: "ERSA",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-BEARING-22316-EW33J-ZKL",
  },
  {
    material: "60004046",
    materialType: "ERSA",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-BRAKE-LINER-MODEL-NO-2-EOT",
  },
  {
    material: "60004047",
    materialType: "ERSA",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-MS-SHAFT-20X1600MM",
  },
  {
    material: "60004077",
    materialType: "ERSA",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-SPRING-MH02171386",
  },
  {
    material: "60004099",
    materialType: "ERSA",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-MS-CHECK-NUT-65X45MM",
  },
  {
    material: "60004110",
    materialType: "ERSA",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-HAMMER-DRILL-BIT-20MM",
  },
  {
    material: "60004117",
    materialType: "ERSA",
    materialGroup: "SM",
    buom: "M",
    status: "approved",
    materialDescription: "SM-PVC-PIPE-1��",
  },
  {
    material: "60004119",
    materialType: "ERSA",
    materialGroup: "SM",
    buom: "M",
    status: "approved",
    materialDescription: "SM-WIRE-ROPE-16MM",
  },
  {
    material: "60004184",
    materialType: "ERSA",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-PUMP-0.37KW-0.5HP-2880RPM",
  },
  {
    material: "60004215",
    materialType: "ERSA",
    materialGroup: "SM",
    buom: "M",
    status: "approved",
    materialDescription: 'SM-RUBBER-BLACK-HOSE-PIPE-1"',
  },
  {
    material: "60004226",
    materialType: "ERSA",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: 'SM-SS-CLAMP-HOSE-1�"',
  },
  {
    material: "60004248",
    materialType: "ERSA",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: 'SM-SS-SCREW-1"',
  },
  {
    material: "60004258",
    materialType: "ERSA",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-SLEEVE-H-2332-WITH-LOCK-NUT",
  },
  {
    material: "60004259",
    materialType: "ERSA",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-NITRILE-RUBBER-OIL-SEAL-160X200X12",
  },
  {
    material: "60004270",
    materialType: "ERSA",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-GI-HEX-WASHER-10MM",
  },
  {
    material: "60004276",
    materialType: "ERSA",
    materialGroup: "SM",
    buom: "KG",
    status: "approved",
    materialDescription: "SM-MS-BRIGHT-BAR-40MM",
  },
  {
    material: "60004280",
    materialType: "ERSA",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-BUSH-MH97958145",
  },
  {
    material: "60004290",
    materialType: "ERSA",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-MINOR-SRV-KIT-MH40900296",
  },
  {
    material: "60004301",
    materialType: "ERSA",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-CONNECTOR-BRAKE-LINE-MH-02310194",
  },
  {
    material: "60004316",
    materialType: "ERSA",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: 'SM-PVC-TEE-1"',
  },
  {
    material: "60004317",
    materialType: "ERSA",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: 'SM-PVC-ELBOW-3/4"',
  },
  {
    material: "60004367",
    materialType: "ERSA",
    materialGroup: "SM",
    buom: "L",
    status: "approved",
    materialDescription: "SM-PAINT",
  },
  {
    material: "60004370",
    materialType: "ERSA",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: 'SM-MS-CLAMP-�"',
  },
  {
    material: "60004463",
    materialType: "ERSA",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-SS-WASHER-PLAIN-6MM",
  },
  {
    material: "60004515",
    materialType: "ERSA",
    materialGroup: "SM",
    buom: "KG",
    status: "approved",
    materialDescription: "SM-NEOPERNE-RUBBER-SHEET-5MM",
  },
  {
    material: "60004538",
    materialType: "ERSA",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-SCREW-SELF-DRILLING-55MM",
  },
  {
    material: "60004555",
    materialType: "ERSA",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: 'SM-FDIESEL-PIPE-48"-5MT-FORKLIFT',
  },
  {
    material: "60004578",
    materialType: "ERSA",
    materialGroup: "SM",
    buom: "KG",
    status: "approved",
    materialDescription: "STR-MS-FLAT-65X8MM",
  },
  {
    material: "60004597",
    materialType: "ERSA",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: 'SM-HYDRAULIC-HOSE-PIPE-3/8"X7MTR',
  },
  {
    material: "60004604",
    materialType: "ERSA",
    materialGroup: "SM",
    buom: "KG",
    status: "approved",
    materialDescription: "STR-MS-ANGLE-25X25X5MM",
  },
  {
    material: "60004619",
    materialType: "ERSA",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-PLYWOOD-7'X4'X18MM",
  },
  {
    material: "60004629",
    materialType: "ERSA",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-SS-SCREW-75X8",
  },
  {
    material: "60004630",
    materialType: "ERSA",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-SS-SCREW-13X6",
  },
  {
    material: "60004659",
    materialType: "ERSA",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-BEARING-30222",
  },
  {
    material: "60004666",
    materialType: "ERSA",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-SS-HOSE-CLAMP-1'1/4\"",
  },
  {
    material: "60004705",
    materialType: "ERSA",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: 'SM-GI-HEX-NIPPLE-1�X2"',
  },
  {
    material: "60004778",
    materialType: "ERSA",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-PISTON-RING-MH02009551",
  },
  {
    material: "60004782",
    materialType: "ERSA",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-FAN-MOTOR-REFIREGTOR",
  },
  {
    material: "60004809",
    materialType: "ERSA",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-RUBBER-OIL-SEAL-280X310X15",
  },
  {
    material: "60004831",
    materialType: "ERSA",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: 'SM-CI-VALVE-FOOT-6"',
  },
  {
    material: "60004839",
    materialType: "ERSA",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: 'SM-MS-COUPLING-FORGES-2"',
  },
  {
    material: "60004842",
    materialType: "ERSA",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: 'SM-PIPE-HYDRAULIC-1/2"X1800MM-WITH-FITTI',
  },
  {
    material: "60004848",
    materialType: "ERSA",
    materialGroup: "SM",
    buom: "KG",
    status: "approved",
    materialDescription: 'SM-NYLON-ROD-4"',
  },
  {
    material: "60004892",
    materialType: "ERSA",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-SS-CSK-ALLEN-BOLT-5X15MM",
  },
  {
    material: "60004924",
    materialType: "ERSA",
    materialGroup: "SM",
    buom: "M",
    status: "approved",
    materialDescription: 'SM-PVC-PIPE-5/8"',
  },
  {
    material: "60004929",
    materialType: "ERSA",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-HYDRAULIC-CYLINDER-KIT-50MM",
  },
  {
    material: "60004944",
    materialType: "ERSA",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-SS-HEX-BOLT-6X12MM",
  },
  {
    material: "60004954",
    materialType: "ERSA",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-BEARING-6203",
  },
  {
    material: "60004977",
    materialType: "ERSA",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-FILTER-FUEL-KIT-4899920000",
  },
  {
    material: "60005043",
    materialType: "ERSA",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-SS-HEX-BOLT-12X65MM",
  },
  {
    material: "60005048",
    materialType: "ERSA",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-GASKET-RING-8''",
  },
  {
    material: "60005054",
    materialType: "ERSA",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-NOZZLE-M-FOAM-9LTR",
  },
  {
    material: "60005062",
    materialType: "ERSA",
    materialGroup: "SM",
    buom: "KG",
    status: "approved",
    materialDescription: "SM-MS-BRIGHT-FLAT-63X12MM",
  },
  {
    material: "60005068",
    materialType: "ERSA",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: 'SM-GI-COUPLING-3"-THREADED',
  },
  {
    material: "60005078",
    materialType: "ERSA",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: 'SM-GI-UNION-1�"',
  },
  {
    material: "60005100",
    materialType: "ERSA",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-DRILL-CHUCK-13MM",
  },
  {
    material: "60005106",
    materialType: "ERSA",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: 'SM-GAUGE-AIR-1/4"-FOR-TYRE',
  },
  {
    material: "60005130",
    materialType: "ERSA",
    materialGroup: "SM",
    buom: "KG",
    status: "approved",
    materialDescription: "SM-EN9-ROUND-BAR-70X2000MM",
  },
  {
    material: "60005152",
    materialType: "ERSA",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-CIRCLIP-INTERNAL-60MM",
  },
  {
    material: "60005166",
    materialType: "ERSA",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-PU-CONNECTOR-MALE-5X8",
  },
  {
    material: "60005171",
    materialType: "ERSA",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: 'SM-GI-NIPPLE-BARREL-1/2"X3"',
  },
  {
    material: "60005172",
    materialType: "ERSA",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-LOCK-WASHER-MB9",
  },
  {
    material: "60005180",
    materialType: "ERSA",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-GREASE-GUN-PIPE",
  },
  {
    material: "60005199",
    materialType: "ERSA",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-SS-HEX-BOLT 8MMX35MM",
  },
  {
    material: "60005200",
    materialType: "ERSA",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-MS-SHAFT-50X210MM",
  },
  {
    material: "60005202",
    materialType: "ERSA",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-GI-BEND-LONG-4�",
  },
  {
    material: "60005224",
    materialType: "ERSA",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: 'SM-BEARING-PULLER-4"',
  },
  {
    material: "60005225",
    materialType: "ERSA",
    materialGroup: "SM",
    buom: "PAC",
    status: "approved",
    materialDescription: "SM-ZEDALLOY-WELDING-ROD-8G",
  },
  {
    material: "60005239",
    materialType: "ERSA",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: 'SM-FLOW-CONTROL-VALVE-1/4"X8MM',
  },
  {
    material: "60005248",
    materialType: "ERSA",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-PIPE-CONNECTION-1/2\"X6'",
  },
  {
    material: "60005262",
    materialType: "ERSA",
    materialGroup: "SM",
    buom: "KG",
    status: "approved",
    materialDescription: "SM-SS304-FLAT-40X3MM",
  },
  {
    material: "60005267",
    materialType: "ERSA",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-STOP-LIGHT-SWITCH-MH02570759",
  },
  {
    material: "60005269",
    materialType: "ERSA",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-FLAING-MH02183563",
  },
  {
    material: "60005291",
    materialType: "ERSA",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-ARALDITE-180GRM",
  },
  {
    material: "60005317",
    materialType: "ERSA",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-WASHER-REAR-02010517",
  },
  {
    material: "60005324",
    materialType: "ERSA",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-ROLL-PIN-0201332",
  },
  {
    material: "60005335",
    materialType: "ERSA",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: 'SM-GI-REDUCER-1/2"X3/4"',
  },
  {
    material: "60005339",
    materialType: "ERSA",
    materialGroup: "SM",
    buom: "KG",
    status: "approved",
    materialDescription: "SM-MS-BRIGHT-HEX-BAR-75MM",
  },
  {
    material: "60005346",
    materialType: "ERSA",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: 'SM-HT-NUT-5/8"',
  },
  {
    material: "60005387",
    materialType: "ERSA",
    materialGroup: "SM",
    buom: "KG",
    status: "approved",
    materialDescription: "SM-SS304-PATTI-10MM",
  },
  {
    material: "60005425",
    materialType: "ERSA",
    materialGroup: "SM",
    buom: "FT",
    status: "approved",
    materialDescription: "SM-RO-PIPE",
  },
  {
    material: "60005469",
    materialType: "ERSA",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-VALVE-KIT-39100170",
  },
  {
    material: "60005471",
    materialType: "ERSA",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-OIL-SENSOR-38200003",
  },
  {
    material: "60005487",
    materialType: "ERSA",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-SOLID-CARBIDE-ENDMILL-CUTTER-6MM",
  },
  {
    material: "60005489",
    materialType: "ERSA",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-O-RING-GASKET-SET-02089942",
  },
  {
    material: "60005498",
    materialType: "ERSA",
    materialGroup: "SM",
    buom: "KG",
    status: "approved",
    materialDescription: "SM-EN8-ROUND-BAR-110MM",
  },
  {
    material: "60005507",
    materialType: "ERSA",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: 'SM-GI-HEX-NIPPLE-1/2"',
  },
  {
    material: "60005508",
    materialType: "ERSA",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: 'SM-GI-HEX-NIPPLE-3/4"',
  },
  {
    material: "60005509",
    materialType: "ERSA",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: 'SM-GI-HEX-NIPPLE-1"',
  },
  {
    material: "60005522",
    materialType: "ERSA",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-CIRCLIP-EXTERNAL-100M",
  },
  {
    material: "60005525",
    materialType: "ERSA",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-SS-ALLEN-KEY-BOLT-8X40MM",
  },
  {
    material: "60005529",
    materialType: "ERSA",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-HT-ALLEN-KEY-BOLT-5X80MM",
  },
  {
    material: "60005541",
    materialType: "ERSA",
    materialGroup: "SM",
    buom: "KG",
    status: "approved",
    materialDescription: "SM-MS-BRIGHT-BAR-12MM",
  },
  {
    material: "60005555",
    materialType: "ERSA",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-SPARE-PARTS-LATHE-MACHINE",
  },
  {
    material: "60005578",
    materialType: "ERSA",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-DOSING-PUMP-RO-PLANT",
  },
  {
    material: "60005593",
    materialType: "ERSA",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-HOSE-MH02310590",
  },
  {
    material: "60005595",
    materialType: "ERSA",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-SENSOR-TEMP-MH02428008",
  },
  {
    material: "60005600",
    materialType: "ERSA",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-SS-STUD-BOLT-10X1MTR",
  },
  {
    material: "60005601",
    materialType: "ERSA",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-BEARING-6310-2Z/C3",
  },
  {
    material: "60005607",
    materialType: "ERSA",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-GEAR-PUMP-3017",
  },
  {
    material: "60005631",
    materialType: "ERSA",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-CARBIDE-ENDMILL-CUTTER-4MM",
  },
  {
    material: "60005633",
    materialType: "ERSA",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: 'SM-DRILL-CHUCK-3/4"',
  },
  {
    material: "60005646",
    materialType: "ERSA",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-HSS-ENDMILL-CUTTER-16MM",
  },
  {
    material: "70000081",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-IMPACT-WRENCH-5000RPM",
  },
  {
    material: "70000082",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-BALL-SCREW",
  },
  {
    material: "70000083",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "EE-RECTIFIER-440V",
  },
  {
    material: "70000105",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "EE-PEDESTAL-FAN-500MM",
  },
  {
    material: "70000116",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-BUSH-SHAFT-175X125X65",
  },
  {
    material: "70000123",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "HG-SHAFT-78X1030",
  },
  {
    material: "70000124",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "HG-BUSH-160X80",
  },
  {
    material: "70000127",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-MS-SHAFT-160X32MM",
  },
  {
    material: "70000132",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-MOTOR-PULLY-3HP",
  },
  {
    material: "70000134",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-MOTOR-0.5HP-0.3KW",
  },
  {
    material: "70000135",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-MOTOR-1HP-1KW-RPM1440",
  },
  {
    material: "70000136",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-MOTOR-0.50HP-0.37KW-1360RPM",
  },
  {
    material: "70000137",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-STARTER-LOADER-F002G20551",
  },
  {
    material: "70000143",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-MOTOR-1/35HP-21W-RPM1280-03Z001412",
  },
  {
    material: "70000144",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-MS-SHAFT-25X1100MM",
  },
  {
    material: "70000147",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-MOTOR-SIDE-COVER-0018",
  },
  {
    material: "70000149",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-MOTOR-4.4HP-3.3KW-RPM1420",
  },
  {
    material: "70000151",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-ROLLER-OD-235X2250MM",
  },
  {
    material: "70000155",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-COOLING-FAN",
  },
  {
    material: "70000156",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-MOTOR-1.5KW-1400-RPM-32380",
  },
  {
    material: "70000157",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-MOTOR-2.5KW-1450-RPM",
  },
  {
    material: "70000159",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-MOTOR-3.7KW-1450-RPM",
  },
  {
    material: "70000160",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-COUPLING-FLUID-OD335",
  },
  {
    material: "70000163",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-FORKLIFT-10MT-HOUSING",
  },
  {
    material: "70000164",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-FORKLIFT-10MT-SLEEVE",
  },
  {
    material: "70000165",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-FORKLIFT-10MT-SHAFT",
  },
  {
    material: "70000167",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-MOTOR-0.06KW-RPM1595-MS5614",
  },
  {
    material: "70000170",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-MOTOR-GREASE-CIRCULATING",
  },
  {
    material: "70000171",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-ELECTROMAGNETIC-BREAK-COIL-230VDC",
  },
  {
    material: "70000172",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-WHEEL-840X750",
  },
  {
    material: "70000174",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-SHAFT-40X1430",
  },
  {
    material: "70000175",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-PUMP-3HP-2.2KW-OSKS-32",
  },
  {
    material: "70000176",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-TRANSFORMER-1KVA",
  },
  {
    material: "70000177",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-CARD-PCB-MSC-3PHASE-01",
  },
  {
    material: "70000185",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-MOTOR-45KW-60HP",
  },
  {
    material: "70000189",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-GRINDER-0.5KW-0.75HP",
  },
  {
    material: "70000190",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-MOTOR-2.2KW-3HP",
  },
  {
    material: "70000191",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-MOTOR-7.5KW-10HP",
  },
  {
    material: "70000193",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-MOTOR-2HP-230V",
  },
  {
    material: "70000194",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-MOTOR-FAN",
  },
  {
    material: "70000195",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-IMPELLER-COVER",
  },
  {
    material: "70000197",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-STIPING-BOX-COVER",
  },
  {
    material: "70000198",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-SS-SHAFT-50X1500MM",
  },
  {
    material: "70000199",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-NUT-20MM",
  },
  {
    material: "70000200",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-BRASS-BUSH-85X125X65",
  },
  {
    material: "70000201",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-SS-BUSH-47X125X50",
  },
  {
    material: "70000203",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-GRINDING-MACHINE",
  },
  {
    material: "70000204",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-VISUALIZER-MULTIFUNTION-LEVEL",
  },
  {
    material: "70000205",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-MIXER-230V-50HZ",
  },
  {
    material: "70000206",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-MOTOR-45KW-60HP-415V",
  },
  {
    material: "70000214",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-MS-SHAFT-55X870MM",
  },
  {
    material: "70000217",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-SHAFT-EN8-70X5960MM",
  },
  {
    material: "70000219",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-MOTOR-AC",
  },
  {
    material: "70000221",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-MOTOR-1/4HP-1440RPM",
  },
  {
    material: "70000222",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-SUBMERSIBLE-PUMP-5HP",
  },
  {
    material: "70000225",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "SET",
    status: "approved",
    materialDescription: "SM-LOVEJOY-COUPLING-L226",
  },
  {
    material: "70000228",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: 'SM-CHAIN-SPROCKET-1/2"',
  },
  {
    material: "70000268",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-MOTOR-32W-860RPM-090106022",
  },
  {
    material: "70000279",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-MS-SHAFT-60X265MM",
  },
  {
    material: "70000281",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-COUNTER-WEIGHT-60MM",
  },
  {
    material: "70000282",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-BUSH-60X90MM",
  },
  {
    material: "70000283",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-PINION-GEAR-11-TEETH",
  },
  {
    material: "70000284",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-PULLY-39.8X12X3.5",
  },
  {
    material: "70000285",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "EE-BEARING-SHEET-COVER",
  },
  {
    material: "70000286",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-BATTERY-LITHIUM-PS-135AH",
  },
  {
    material: "70000287",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-EXHAUST-FAN",
  },
  {
    material: "70000289",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "HG-PULLY-6-GROOVE",
  },
  {
    material: "70000291",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-SHAFT-60X1000MM",
  },
  {
    material: "70000301",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-MS-SHAFT-28X375MM",
  },
  {
    material: "70000302",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-LUPATO-TOOL-PLATE-295X50",
  },
  {
    material: "70000305",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-CI-PULLY-262X210MM",
  },
  {
    material: "70000309",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-SHAFT-31X325MM",
  },
  {
    material: "70000310",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-BEARING-COVER-6032",
  },
  {
    material: "70000311",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-SHAFT-15X203",
  },
  {
    material: "70000313",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-SHAFT-30X400",
  },
  {
    material: "70000314",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-GEAR-14TEETH",
  },
  {
    material: "70000319",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-SPROCKET-30X17THEETH",
  },
  {
    material: "70000330",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: 'SM-CI-PULLEY-4"',
  },
  {
    material: "70000332",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-TRANSMISSION-CONVERTER-ASSEMBLY-10T",
  },
  {
    material: "70000335",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-PULLEY-SHAFT125MMX24X8X3.5",
  },
  {
    material: "70000336",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-PULLEY-MOTOR-100MMX24X8X3.5",
  },
  {
    material: "70000338",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-VALVE-BUTTERFLY-485MM",
  },
  {
    material: "70000339",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-VALVE-BUTTERFLY-SEAL-485MM",
  },
  {
    material: "70000341",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-MOTOR-60HP-1500RPM-FOOT-MOUNTED",
  },
  {
    material: "70000354",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-CALIBRATION-HEAD-300X370",
  },
  {
    material: "70000356",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-SUBMERSIBLE-MOTOR-5HP-3.7KW-415V",
  },
  {
    material: "70000357",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "SET",
    status: "approved",
    materialDescription: "SM-SS-COUPLING-KTR-24",
  },
  {
    material: "70000360",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-ELECTROMAGNETIC-BREAK-COIL-24VDC",
  },
  {
    material: "70000366",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-MS-SHAFT-40X1750",
  },
  {
    material: "70000367",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-CI-PULLEY-28X8X3.5",
  },
  {
    material: "70000368",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-HELICAL-RACK-LEFT-40X40X2075MM",
  },
  {
    material: "70000369",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-HELICAL-RACK-RIGHT-40X40X2075MM",
  },
  {
    material: "70000370",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-HAND-CUTTING-MACHINE-230V-5.4AMP-9815",
  },
  {
    material: "70000371",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-MS-SHAFT-18X141MM",
  },
  {
    material: "70000372",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-HOUSING-30X90",
  },
  {
    material: "70000373",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-GEAR-BEVEL-33",
  },
  {
    material: "70000376",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-MS-PLATE-260X200X10MM",
  },
  {
    material: "70000377",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-WHEEL-35X10X5X40THEET",
  },
  {
    material: "70000378",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-MS-BOLT-52X340",
  },
  {
    material: "70000393",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-HYDRAULIC-PIPE",
  },
  {
    material: "70000397",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-BREAKER-MACHINE-GSH-16-PROFESSIONAL",
  },
  {
    material: "70000398",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-CARD-REMOTE-PCP-SPLIT-AC",
  },
  {
    material: "70000405",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-MS-SHAFT-44.7X153MM",
  },
  {
    material: "70000406",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-MS-PISTON-ROD-�35X2130MM",
  },
  {
    material: "70000407",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-MS-SLEEVE-48.8X65X162",
  },
  {
    material: "70000408",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-MS-BUSH-65X85X133.5MM",
  },
  {
    material: "70000410",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-STRAPPING-MACHINE-SEMI-AUTOMATIC",
  },
  {
    material: "70000411",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-IMPELLER-50MM",
  },
  {
    material: "70000412",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-MS-SHAFT-58X1230MM",
  },
  {
    material: "70000413",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-MS-BUSH-58X75X200MM",
  },
  {
    material: "70000414",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-MS-NUT-M50",
  },
  {
    material: "70000415",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "BUCKET-ELEVATOR BE 6, 7, 8",
  },
  {
    material: "70000418",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-BOLT-MOULD-M25X125MM",
  },
  {
    material: "70000419",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-MS-SHAFT48X1037",
  },
  {
    material: "70000420",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-HOUSING-ID106MM",
  },
  {
    material: "70000421",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-HOUSING-ID86MM",
  },
  {
    material: "70000423",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "EE-MOTOR-0.18KW-0.7A-1400RPM",
  },
  {
    material: "70000424",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "EE-DRIVE-CIMR-G7A4011",
  },
  {
    material: "70000427",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-DRIVE-G7-15KW-J007XF072310001",
  },
  {
    material: "70000428",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-DRIVE-F7-15KW-JL086R7FD100282",
  },
  {
    material: "70000430",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: 'SM-CI-PULLEY-3GROOVE-5"',
  },
  {
    material: "70000433",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "HG-CI-PULLEY-4GROOVE-300MM",
  },
  {
    material: "70000434",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "HG-CI-PULLEY-4GROOVE-110MM",
  },
  {
    material: "70000439",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "EE-MOBILE-BLACKBERRY-8520-Mr. NISHIT",
  },
  {
    material: "70000440",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "EE-STARTER-FORKLIFT-3T-DN-09-F-0682",
  },
  {
    material: "70000441",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-MS-SHAFT-50X2500MM",
  },
  {
    material: "70000446",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "EE-STARTER-FORKLIFT-5T-DN-09-G-1895",
  },
  {
    material: "70000447",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-BATTERY-EXIDE-12V",
  },
  {
    material: "70000448",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-DYNAMO-DG-1500KVA",
  },
  {
    material: "70000451",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-MS-SHAFT-1185MM",
  },
  {
    material: "70000452",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-MS-SHAFT-1145MM",
  },
  {
    material: "70000453",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "EE-STARTER-FORKLIFT-3T-DN-09-F-0527",
  },
  {
    material: "70000456",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-PINION-�120MMX170MM",
  },
  {
    material: "70000457",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-LOVEJOY-COUPLING-L225",
  },
  {
    material: "70000464",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "SET",
    status: "approved",
    materialDescription: "SM-SCREW-JACK-48X400MM-WITH-BUSH",
  },
  {
    material: "70000468",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-MS-ROUND-PLATE-150MM",
  },
  {
    material: "70000469",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-MS-ROLLER-101X1700MM",
  },
  {
    material: "70000473",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-MS-ROLLER-90X75MM",
  },
  {
    material: "70000474",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-DYNAMO-FORKLIFT-3T-DN-09-F-0682",
  },
  {
    material: "70000476",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-MS-SHAFT-50X950MM",
  },
  {
    material: "70000477",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-ROLLER-END-RUBBER-101X1700MM",
  },
  {
    material: "70000479",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-MOTOR-ROTOR-60X10X3.5",
  },
  {
    material: "70000480",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-MS-COUPLING-24X8X4",
  },
  {
    material: "70000481",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: 'SM-MS-CHAIN-SPROCKET-DUPLEX-1/2"X16TEETH',
  },
  {
    material: "70000486",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-MOTOR-GRINDER-RPM2800-HP5",
  },
  {
    material: "70000487",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-MS-PLATE-480X10MM",
  },
  {
    material: "70000488",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-CI-PULLEY-2GROOVE-150MM",
  },
  {
    material: "70000490",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-CI-PULLEY-3GROOVE-150MM-B-TYPE",
  },
  {
    material: "70000491",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-RUBBER-ROLLER-101X1700MM",
  },
  {
    material: "70000492",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-BRASS-LINER-20X30X2130MM",
  },
  {
    material: "70000493",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-MS-GEAR-210X100MM",
  },
  {
    material: "70000494",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-ROTOR-SHAFT-35X400MM",
  },
  {
    material: "70000495",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-MS-MOTOR-SHAFT-8X53MM",
  },
  {
    material: "70000496",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-MS-SHAFT-48X1132MM",
  },
  {
    material: "70000497",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-MS-FLANGE-F-50",
  },
  {
    material: "70000499",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-DYNAMO-FORKLIFT-3T-DN-09-F-0527",
  },
  {
    material: "70000500",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "EE-WEIGHING-SCALE-CRS15T",
  },
  {
    material: "70000501",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-SLURRY-PUMP-BODY",
  },
  {
    material: "70000502",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-WARM-GEAR-60X155-40TEETH",
  },
  {
    material: "70000503",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-MS-MOTOR-COVER-108X255MM",
  },
  {
    material: "70000504",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-EN8-SHAFT-42X1205",
  },
  {
    material: "70000505",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-BRASS-NUT-90X80",
  },
  {
    material: "70000506",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-MS-SHAFT-35X300MM",
  },
  {
    material: "70000507",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-MS-WARM-GEAR-ID-38",
  },
  {
    material: "70000508",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-HOUSING-300X260X100MM",
  },
  {
    material: "70000509",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "HG-LOVEJOY-COUPLING-L110",
  },
  {
    material: "70000512",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "HG-GANGSAW-BLADE-4350X180X2.5",
  },
  {
    material: "70000513",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-MS-SHAFT-48X570MM",
  },
  {
    material: "70000514",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-MS-HOUSING-65X225MM",
  },
  {
    material: "70000515",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-MS-SHAFT-50X900M",
  },
  {
    material: "70000516",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-MS-PINION-50MMX27TEETH",
  },
  {
    material: "70000519",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-MS-BOLT-M48X175",
  },
  {
    material: "70000520",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-MS-SHAFT-50X1685",
  },
  {
    material: "70000521",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "EE-DRIVE-CIMR-47A242P2",
  },
  {
    material: "70000522",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-MS-SHAFT-�39X79MM",
  },
  {
    material: "70000523",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-MS-BREAK-LINER-150X100MM",
  },
  {
    material: "70000524",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-MS-SHAFT-100X1155MM",
  },
  {
    material: "70000525",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-CHECK-NUT-70X145MM",
  },
  {
    material: "70000526",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-BRASS-BUSH-215X400MM",
  },
  {
    material: "70000527",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "EE-MOTOR-0.1HP-0.35A-1-PHASE",
  },
  {
    material: "70000528",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-SILICON-TUBE-UPPER-DOOR-37X26X7000",
  },
  {
    material: "70000529",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-SILICON-TUBE-LOWER-DOOR-37X26X8500",
  },
  {
    material: "70000530",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-LINER-150X104X5MM",
  },
  {
    material: "70000531",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-MS-SHAFT-38X505MM",
  },
  {
    material: "70000532",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-MS-SHAFT-45X900MM",
  },
  {
    material: "70000533",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-MS-SHAFT-50X2550MM",
  },
  {
    material: "70000534",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "EE-DRIVE-AC-1.5KW-CIMR-F7B41PS",
  },
  {
    material: "70000535",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "EE-STARTER-FORKLIFT-10T-DN-09-F-0677",
  },
  {
    material: "70000541",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-CI-PLATE-18MMX560MM",
  },
  {
    material: "70000542",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-MS-SHAFT-24X302MM",
  },
  {
    material: "70000543",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-MS-HOUSING-170X350",
  },
  {
    material: "70000544",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-GEAR-258X84X26TEETH",
  },
  {
    material: "70000545",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-MS-SHAFT-55X160MM",
  },
  {
    material: "70000547",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-MS-SHAFT-28X380MM",
  },
  {
    material: "70000548",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-CI-MOTOR-COVER-72X250MM",
  },
  {
    material: "70000549",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-MS-BREAK-LINER-55X150MM",
  },
  {
    material: "70000551",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "EE-PRESSURE-SWITCH-FOR-WATER-PUMP",
  },
  {
    material: "70000552",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-MS-SHAFT-55X590MM",
  },
  {
    material: "70000553",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-MOTOR-SIDE-COVER-75X440MM",
  },
  {
    material: "70000554",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: 'EE-CAMERA-COLOR-BOX-1/3"',
  },
  {
    material: "70000555",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "EE-CAMERA-SDZ300",
  },
  {
    material: "70000556",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "EE-CAMERA-EVERFOCUS-SPEED-DOME",
  },
  {
    material: "70000559",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-CALIBRATION-RING650X530X60",
  },
  {
    material: "70000560",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "EE-SMPS-DC-120-24",
  },
  {
    material: "70000561",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-BREAK-LINER-30X58X28TEETH",
  },
  {
    material: "70000562",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-TROLLEY-WHEEL-130X450",
  },
  {
    material: "70000568",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-MS-SHAFT-40X250MM",
  },
  {
    material: "70000571",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-GEAR-BOX-K-732",
  },
  {
    material: "70000573",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: 'SM-CI-FLANGE-COUPLING-10"',
  },
  {
    material: "70000574",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-MS-SHAFT-45X2750MM",
  },
  {
    material: "70000575",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-MS-SCREW-LEAD-30X275MM",
  },
  {
    material: "70000576",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-MS-SHAFT-50X2530MM",
  },
  {
    material: "70000577",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-GEAR-BOX-330X300X155-SERIAL NO. 09092",
  },
  {
    material: "70000579",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-GANGSAW-HOLDER",
  },
  {
    material: "70000580",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-IMPELLER-295X42MM",
  },
  {
    material: "70000582",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-MS-COVER-CLUTCH-150X105",
  },
  {
    material: "70000584",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-MS-SHAFT-28X384MM",
  },
  {
    material: "70000587",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-HYDRAULIC-CYLINDER-35X1200",
  },
  {
    material: "70000589",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-MS-SHAFT-45X250MM",
  },
  {
    material: "70000591",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-ENGINE-FORKLIFT-5T",
  },
  {
    material: "70000593",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: 'SM-CI-PULLEY-8GROOVE-300MM"',
  },
  {
    material: "70000595",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-MS-SHAFT-130X670MM",
  },
  {
    material: "70000681",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "CHECKNUT KM-10",
  },
  {
    material: "70000697",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-BREAK-LINER-115X5MM",
  },
  {
    material: "70000701",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "M.S Roller SEI line",
  },
  {
    material: "70000702",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: 'Chain Sprocket simlex 1/2"',
  },
  {
    material: "70000704",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-SS304-PLATE-3450X830X2MM",
  },
  {
    material: "70000705",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-MS-SHAFT-120XX670MM",
  },
  {
    material: "70000706",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-MS-SHAFT-80X1000MM",
  },
  {
    material: "70000711",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-CI-PULLEY-2GROOVE-125MM-B-SECTION",
  },
  {
    material: "70000713",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-MS-ROLLER-SEI-RESIN-LINE",
  },
  {
    material: "70000715",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-MS-WHEEL-290X126X90MM",
  },
  {
    material: "70000727",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-SUBMERSIBLE-MOTOR-7.5HP-5.5KW-415KW",
  },
  {
    material: "70000729",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-MS-SHAFT-�50X800MM",
  },
  {
    material: "70000730",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-MS-HOUSING-170X600MM",
  },
  {
    material: "70000734",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-TEFLON-BUSH-140X40X80MM",
  },
  {
    material: "70000735",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-TEFLON-BUSH-165X75X50MM",
  },
  {
    material: "70000736",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-PULLY-9-GROOVE",
  },
  {
    material: "70000738",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-STAR-COUPLING-F-110-FERNER",
  },
  {
    material: "70000789",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-MOTOR-5HP-1440RPM",
  },
  {
    material: "70000798",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-MS-SHAFT-�50X420MM",
  },
  {
    material: "70000801",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "EE-MOTOR-0.06KW-1330RPM",
  },
  {
    material: "70000803",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-MOTOR-20HP-15KW-1400RPM",
  },
  {
    material: "70000804",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-EN24-ECCENTRIC-PIN-140X120MM-LONG",
  },
  {
    material: "70000805",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-BRASS-SPINDLE-BUSH-85X390MM",
  },
  {
    material: "70000806",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-SS304-PLATE-2MM FOR OVEN",
  },
  {
    material: "70000807",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "EE-MOTOR-50W-100RPM-24VDC",
  },
  {
    material: "70000808",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "SET",
    status: "approved",
    materialDescription: "SM-CLUTCH-DISCS-LINING-FORKLIFT",
  },
  {
    material: "70000810",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-SUBMERSIBLE-MOTOR-2.2KW-3HP",
  },
  {
    material: "70000816",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-TIMING-PULLY-60X100MM",
  },
  {
    material: "70000821",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-MS-V-BLOCK-190X60X35MM",
  },
  {
    material: "70000825",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-ASSENTRIC-PIN-150X370MM",
  },
  {
    material: "70000826",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-ROTOR-20X240MM",
  },
  {
    material: "70000827",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: 'SM-MS-CHAIN-SPROCKET-DUPLEX-�"-19TEETH',
  },
  {
    material: "70000832",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-VALVE-SEAL-490X435X110MM",
  },
  {
    material: "70000833",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-MS-SHAFT-65X150MM",
  },
  {
    material: "70000834",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-MS-SHAFT-ROTOR-38X487MM",
  },
  {
    material: "70000837",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-MS-CONNETING-ROD-600X4300MM",
  },
  {
    material: "70000838",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-GREASE-GUN-25KG",
  },
  {
    material: "70000839",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-SHAFT-FALANGH-JOINT-60X250-200X16MM",
  },
  {
    material: "70000840",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-EN24-SQUARE-BAR-94X94MM",
  },
  {
    material: "70000841",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-MS-BUSH-35X650MM",
  },
  {
    material: "70000842",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "SET",
    status: "approved",
    materialDescription: "SM-TRANSMISSION-OVERHAULING-5T",
  },
  {
    material: "70000843",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-GEAR-BOX-SKFA180Y4160M-11-9.56",
  },
  {
    material: "70000845",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-DYNAMO-FORKLIFT-3T-DN-09-G-1895",
  },
  {
    material: "70000851",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-OIL-HEATING-TANK",
  },
  {
    material: "70000854",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-MS-MAIN-SHAFT-WITH-ECCENTRIC-KEDA-6",
  },
  {
    material: "70000856",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-MS-PLATE�450X8MM",
  },
  {
    material: "70000859",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-MS-SHAFT-20X150MM",
  },
  {
    material: "70000863",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-MS-PLATE-830X100X20MM",
  },
  {
    material: "70000864",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-MOTOR-3.7KW-5HP-960RPM",
  },
  {
    material: "70000865",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-EN09-ROLLER-SHAFT-124X290MM-3-SLOTTED",
  },
  {
    material: "70000866",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-MS-HYDROLIC-PISTON-60X710MM",
  },
  {
    material: "70000867",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-MS-SHAFT-�35X150MM",
  },
  {
    material: "70000868",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-MS-SHAFT-�38X500MM",
  },
  {
    material: "70000869",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-MS-SHAFT-�38.68X80MM",
  },
  {
    material: "70000870",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-BRONZE-BUSH-81X57X91MM",
  },
  {
    material: "70000876",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-MS-PINION-40X250MM",
  },
  {
    material: "70000877",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-MS-BEVEL-GEAR-40X250MM",
  },
  {
    material: "70000885",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-CI-BUSH-L190XO95XI61XTHI15MM",
  },
  {
    material: "70000897",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-MS-PINION-GEAR-17TEETH",
  },
  {
    material: "70000907",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-MS-SHAFT-100X140MM",
  },
  {
    material: "70000930",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-MS-MOTOR-ROTOR-SHAFT-55X600MM",
  },
  {
    material: "70000942",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "EE-MOTOR-3KW-4HP-1400RPM",
  },
  {
    material: "70000946",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-MS-SHAFT-�25X470MM",
  },
  {
    material: "70000948",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-COMPRESSOR-AIR-COOLER-MM75",
  },
  {
    material: "70000950",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-MS-HOUSING-180X380MM",
  },
  {
    material: "70000958",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-MS-BUSH-40X60",
  },
  {
    material: "70000961",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-MS-SHAFT-40X150MM",
  },
  {
    material: "70000964",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-MS-BRACKET-150X150MM",
  },
  {
    material: "70000971",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-MS-DOWEL-PIN-25X75MM",
  },
  {
    material: "70000972",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-MS-SHAFT-55X965MM",
  },
  {
    material: "70000979",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-WELDING-MACHINE",
  },
  {
    material: "70000996",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: 'SM-VALVE-BALL-6"',
  },
  {
    material: "70001005",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-MS-PULLEY-100X80mm",
  },
  {
    material: "70001020",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-MS-COVER-BEARING-25X145MM",
  },
  {
    material: "70001025",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-MS-FLANGE-153MM",
  },
  {
    material: "70001060",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-MS-SHAFT-60X2530MM",
  },
  {
    material: "70001065",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-STUD-BOLT-35X700MM-FOR-VIBRATOR-MC",
  },
  {
    material: "70001084",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-MS-HOUSING-410MM",
  },
  {
    material: "70001087",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-ALUMINIUM-MOTOR-COVER-20MMX200MM",
  },
  {
    material: "70001128",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-MS-COUPLING-100MM",
  },
  {
    material: "70001202",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-EN8-SHAFT-300X1950MM",
  },
  {
    material: "70001235",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-TROLLEY-BRIDGE-CUTTING-MACHINE",
  },
  {
    material: "70001270",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "KG",
    status: "approved",
    materialDescription: "SS SCRAP",
  },
  {
    material: "70001277",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "KG",
    status: "approved",
    materialDescription: "SCRAP",
  },
  {
    material: "70001289",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "EE-STARTER-FORKLIFT-3T-DN-09-1362",
  },
  {
    material: "70001293",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-UV-EQUIPMENT-RESINLINE-SLAB",
  },
  {
    material: "70001318",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "SM-ELECTRIC-HEATER-1000W",
  },
  {
    material: "70001319",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "KG",
    status: "approved",
    materialDescription: "SM-ALUNINUM-SCRAP",
  },
  {
    material: "70001381",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "EE- BREAK-COIL-ELECTRIC-400VOLT,50HZ,3PH",
  },
  {
    material: "70001393",
    materialType: "UNBW",
    materialGroup: "SM",
    buom: "NOS",
    status: "approved",
    materialDescription: "EE-TRANSFORMER-CONTROL-500VA",
  },
];
