import { MaterialRateValues } from "./components/mr-request-forms/schema";

export const materialRequest: MaterialRateValues[] = [
  {
    reqId: "MR2500004",
    srNo: "10",
    materialCode: "60003097",
    description: 'SM-PU-ELBOW-1/8"X8MM',
    materialGroup: "SM",
    qtyReq: "1",
    qtyApproved: "1",
    qtyIssued: "1",
    uom: "NOS",
    materialType: "ERSA",
    purpose: "OK",
    status: "Partially Open",
    createdDate: "10/1/2023",
    approvalDate: "10/1/2023",
    createdBy: "snehal",
    approvedBy: "himanshu",
  },
  {
    reqId: "MR2500004",
    srNo: "20",
    materialCode: "60003099",
    description: "SM-SS-ALLEN-BOLT-5X12MM",
    materialGroup: "SM",
    qtyReq: "1",
    qtyApproved: "1",
    qtyIssued: "1",
    uom: "NOS",
    materialType: "ERSA",
    purpose: "OK",
    status: "Partially Open",
    createdDate: "10/1/2023",
    approvalDate: "10/1/2023",
    createdBy: "snehal",
    approvedBy: "himanshu",
  },
  {
    reqId: "MR2500004",
    srNo: "30",
    materialCode: "60003101",
    description: "SM-AIR-FILTER-21702911-500KVA-DG",
    materialGroup: "SM",
    qtyReq: "2",
    qtyApproved: "2",
    qtyIssued: "2",
    uom: "NOS",
    materialType: "ERSA",
    purpose: "OK",
    status: "Partially Open",
    createdDate: "10/1/2023",
    approvalDate: "10/1/2023",
    createdBy: "snehal",
    approvedBy: "himanshu",
  },
  {
    reqId: "MR2500004",
    srNo: "40",
    materialCode: "60003117",
    description: 'SM-VALVE-SOLENOID-5/2"X1/4"-24VDC-MAKE',
    materialGroup: "SM",
    qtyReq: "2",
    qtyApproved: "2",
    qtyIssued: "2",
    uom: "NOS",
    materialType: "ERSA",
    purpose: "OK",
    status: "Partially Open",
    createdDate: "10/1/2023",
    approvalDate: "10/1/2023",
    createdBy: "snehal",
    approvedBy: "himanshu",
  },
  {
    reqId: "MR2500004",
    srNo: "50",
    materialCode: "60003119",
    description: "EE-TUBE-LIGH-T5-FITTING-14W-PHILIPS",
    materialGroup: "SM",
    qtyReq: "3",
    qtyApproved: "3",
    qtyIssued: "3",
    uom: "NOS",
    materialType: "ERSA",
    purpose: "OK",
    status: "Partially Open",
    createdDate: "10/1/2023",
    approvalDate: "10/1/2023",
    createdBy: "snehal",
    approvedBy: "himanshu",
  },
  {
    reqId: "MR2500005",
    srNo: "10",
    materialCode: "60003127",
    description: "SM-PVC-MOTOR-COOLING-FAN-15/25HP",
    materialGroup: "SM",
    qtyReq: "3",
    qtyApproved: "3",
    qtyIssued: "3",
    uom: "NOS",
    materialType: "ERSA",
    purpose: "OK",
    status: "Partially Open",
    createdDate: "10/1/2023",
    approvalDate: "10/1/2023",
    createdBy: "snehal",
    approvedBy: "himanshu",
  },
  {
    reqId: "MR2500005",
    srNo: "20",
    materialCode: "60003141",
    description: "SM-HT-HEX-BOLT-20X60MM",
    materialGroup: "SM",
    qtyReq: "23",
    qtyApproved: "23",
    qtyIssued: "23",
    uom: "NOS",
    materialType: "ERSA",
    purpose: "OK",
    status: "Partially Open",
    createdDate: "10/1/2023",
    approvalDate: "10/1/2023",
    createdBy: "snehal",
    approvedBy: "himanshu",
  },
  {
    reqId: "MR2500005",
    srNo: "30",
    materialCode: "60003146",
    description: "SM-HT-HEX-BOLT-12X35MM",
    materialGroup: "SM",
    qtyReq: "4",
    qtyApproved: "4",
    qtyIssued: "4",
    uom: "NOS",
    materialType: "ERSA",
    purpose: "OK",
    status: "Open",
    createdDate: "10/1/2023",
    approvalDate: "10/1/2023",
    createdBy: "snehal",
    approvedBy: "himanshu",
  },
  {
    reqId: "MR2500005",
    srNo: "40",
    materialCode: "60003152",
    description: 'SM-WOOD-CUTTING-BLADE-4"',
    materialGroup: "SM",
    qtyReq: "2",
    qtyApproved: "2",
    qtyIssued: "2",
    uom: "NOS",
    materialType: "ERSA",
    purpose: "OK",
    status: "Partially Open",
    createdDate: "10/1/2023",
    approvalDate: "10/1/2023",
    createdBy: "snehal",
    approvedBy: "himanshu",
  },
  {
    reqId: "MR2500005",
    srNo: "50",
    materialCode: "60003178",
    description: "SM-BEARING-6005-ZZ",
    materialGroup: "SM",
    qtyReq: "22",
    qtyApproved: "22",
    qtyIssued: "22",
    uom: "NOS",
    materialType: "ERSA",
    purpose: "OK",
    status: "Partially Open",
    createdDate: "10/1/2023",
    approvalDate: "10/1/2023",
    createdBy: "snehal",
    approvedBy: "himanshu",
  },
  {
    reqId: "MR2500005",
    srNo: "60",
    materialCode: "60003224",
    description: "SM-EMERY-PAPER-100",
    materialGroup: "SM",
    qtyReq: "2",
    qtyApproved: "2",
    qtyIssued: "2",
    uom: "NOS",
    materialType: "ERSA",
    purpose: "OK",
    status: "Partially Open",
    createdDate: "10/1/2023",
    approvalDate: "10/1/2023",
    createdBy: "snehal",
    approvedBy: "himanshu",
  },
  {
    reqId: "MR2500005",
    srNo: "70",
    materialCode: "60003276",
    description: 'SM-NEOPRENE-RUBBER-BELLOW-COUPLING-6"',
    materialGroup: "SM",
    qtyReq: "3",
    qtyApproved: "3",
    qtyIssued: "3",
    uom: "NOS",
    materialType: "ERSA",
    purpose: "OK",
    status: "Open",
    createdDate: "10/1/2023",
    approvalDate: "10/1/2023",
    createdBy: "snehal",
    approvedBy: "himanshu",
  },
  {
    reqId: "MR2500005",
    srNo: "80",
    materialCode: "60003279",
    description: "SM-MS-SCREW-8X38MM",
    materialGroup: "SM",
    qtyReq: "",
    qtyApproved: "2",
    qtyIssued: "2",
    uom: "NOS",
    materialType: "ERSA",
    purpose: "OK",
    status: "Partially Open",
    createdDate: "10/1/2023",
    approvalDate: "10/1/2023",
    createdBy: "snehal",
    approvedBy: "himanshu",
  },
  {
    reqId: "MR2500006",
    srNo: "10",
    materialCode: "60003288",
    description: 'SM-MS-REDUCER-�"X3/4"',
    materialGroup: "SM",
    qtyReq: "2",
    qtyApproved: "2",
    qtyIssued: "2",
    uom: "NOS",
    materialType: "ERSA",
    purpose: "OK",
    status: "Partially Open",
    createdDate: "10/1/2023",
    approvalDate: "10/1/2023",
    createdBy: "snehal",
    approvedBy: "himanshu",
  },
  {
    reqId: "MR2500006",
    srNo: "20",
    materialCode: "60003306",
    description: "SM-PVC-PIPE-FLEXIBLE-20MM",
    materialGroup: "SM",
    qtyReq: "2",
    qtyApproved: "2",
    qtyIssued: "2",
    uom: "M",
    materialType: "ERSA",
    purpose: "OK",
    status: "Partially Open",
    createdDate: "10/1/2023",
    approvalDate: "10/1/2023",
    createdBy: "snehal",
    approvedBy: "himanshu",
  },
  {
    reqId: "MR2500006",
    srNo: "30",
    materialCode: "60003314",
    description: "SM-JOINT-MH02016650",
    materialGroup: "SM",
    qtyReq: "4",
    qtyApproved: "4",
    qtyIssued: "4",
    uom: "NOS",
    materialType: "ERSA",
    purpose: "OK",
    status: "Closed",
    createdDate: "10/1/2023",
    approvalDate: "10/1/2023",
    createdBy: "snehal",
    approvedBy: "himanshu",
  },
  {
    reqId: "MR2500006",
    srNo: "40",
    materialCode: "60003336",
    description: "SM-CIRCLIP-INTERNAL-90MM",
    materialGroup: "SM",
    qtyReq: "3",
    qtyApproved: "3",
    qtyIssued: "3",
    uom: "NOS",
    materialType: "ERSA",
    purpose: "OK",
    status: "Open",
    createdDate: "10/1/2023",
    approvalDate: "10/1/2023",
    createdBy: "snehal",
    approvedBy: "himanshu",
  },
  {
    reqId: "MR2500006",
    srNo: "50",
    materialCode: "60003347",
    description: "SM-T-ROLL-BEARING-MH-55300006",
    materialGroup: "SM",
    qtyReq: "3",
    qtyApproved: "3",
    qtyIssued: "3",
    uom: "NOS",
    materialType: "ERSA",
    purpose: "OK",
    status: "Open",
    createdDate: "10/1/2023",
    approvalDate: "10/1/2023",
    createdBy: "snehal",
    approvedBy: "himanshu",
  },
  {
    reqId: "MR2500006",
    srNo: "60",
    materialCode: "60003350",
    description: "SM-REV-HORN-MH-59073004",
    materialGroup: "SM",
    qtyReq: "2",
    qtyApproved: "2",
    qtyIssued: "2",
    uom: "NOS",
    materialType: "ERSA",
    purpose: "OK",
    status: "Open",
    createdDate: "10/1/2023",
    approvalDate: "10/1/2023",
    createdBy: "snehal",
    approvedBy: "himanshu",
  },
  {
    reqId: "MR2500006",
    srNo: "70",
    materialCode: "60003355",
    description: "SM-PVC-PIPE-FLEXIBLE-25MM",
    materialGroup: "SM",
    qtyReq: "4",
    qtyApproved: "4",
    qtyIssued: "4",
    uom: "M",
    materialType: "ERSA",
    purpose: "OK",
    status: "Open",
    createdDate: "10/1/2023",
    approvalDate: "10/1/2023",
    createdBy: "snehal",
    approvedBy: "himanshu",
  },
  {
    reqId: "MR2500006",
    srNo: "80",
    materialCode: "60003359",
    description: "SM-STRIP-REVERSE-HORN-MH02364890",
    materialGroup: "SM",
    qtyReq: "4",
    qtyApproved: "4",
    qtyIssued: "4",
    uom: "NOS",
    materialType: "ERSA",
    purpose: "OK",
    status: "Open",
    createdDate: "10/1/2024",
    approvalDate: "10/1/2024",
    createdBy: "snehal",
    approvedBy: "himanshu",
  },
  {
    reqId: "MR2500007",
    srNo: "10",
    materialCode: "60003360",
    description: "SM-SWITCH-MH02292630",
    materialGroup: "SM",
    qtyReq: "5",
    qtyApproved: "5",
    qtyIssued: "5",
    uom: "NOS",
    materialType: "ERSA",
    purpose: "OK",
    status: "Open",
    createdDate: "10/1/2024",
    approvalDate: "10/1/2024",
    createdBy: "snehal",
    approvedBy: "himanshu",
  },
  {
    reqId: "MR2500007",
    srNo: "20",
    materialCode: "60003365",
    description: "SM-RUBBER-CORD-6MM",
    materialGroup: "SM",
    qtyReq: "54",
    qtyApproved: "54",
    qtyIssued: "54",
    uom: "M",
    materialType: "ERSA",
    purpose: "OK",
    status: "Open",
    createdDate: "10/1/2024",
    approvalDate: "10/1/2024",
    createdBy: "snehal",
    approvedBy: "himanshu",
  },
  {
    reqId: "MR2500007",
    srNo: "30",
    materialCode: "60003385",
    description: "SM-PAINT-APCOLITE-ENAMEL-PHIROZA-ASIAN",
    materialGroup: "SM",
    qtyReq: "5",
    qtyApproved: "5",
    qtyIssued: "5",
    uom: "L",
    materialType: "ERSA",
    purpose: "OK",
    status: "Open",
    createdDate: "10/1/2024",
    approvalDate: "10/1/2024",
    createdBy: "snehal",
    approvedBy: "himanshu",
  },
  {
    reqId: "MR2500007",
    srNo: "40",
    materialCode: "60003410",
    description: "SM-RUBBER-CORD-3.5MM",
    materialGroup: "SM",
    qtyReq: "65",
    qtyApproved: "65",
    qtyIssued: "65",
    uom: "M",
    materialType: "ERSA",
    purpose: "OK",
    status: "Open",
    createdDate: "10/1/2024",
    approvalDate: "10/1/2024",
    createdBy: "snehal",
    approvedBy: "himanshu",
  },
  {
    reqId: "MR2500007",
    srNo: "50",
    materialCode: "60003414",
    description: "SM-CI-BRACKET-��X18�",
    materialGroup: "SM",
    qtyReq: "2",
    qtyApproved: "2",
    qtyIssued: "2",
    uom: "SET",
    materialType: "ERSA",
    purpose: "OK",
    status: "Open",
    createdDate: "10/1/2024",
    approvalDate: "10/1/2024",
    createdBy: "snehal",
    approvedBy: "himanshu",
  },
  {
    reqId: "MR2500007",
    srNo: "60",
    materialCode: "60003421",
    description: "SM-NBR-OIL-SEAL-22X42X10MM",
    materialGroup: "SM",
    qtyReq: "45",
    qtyApproved: "45",
    qtyIssued: "45",
    uom: "NOS",
    materialType: "ERSA",
    purpose: "OK",
    status: "Open",
    createdDate: "10/1/2024",
    approvalDate: "10/1/2024",
    createdBy: "snehal",
    approvedBy: "himanshu",
  },
  {
    reqId: "MR2500007",
    srNo: "70",
    materialCode: "60003426",
    description: "SM-BREAK-LINER-100X1000X8MM",
    materialGroup: "SM",
    qtyReq: "4",
    qtyApproved: "4",
    qtyIssued: "4",
    uom: "NOS",
    materialType: "ERSA",
    purpose: "OK",
    status: "Open",
    createdDate: "10/1/2024",
    approvalDate: "10/1/2024",
    createdBy: "snehal",
    approvedBy: "himanshu",
  },
  {
    reqId: "MR2500007",
    srNo: "80",
    materialCode: "60003435",
    description: 'SM-COUPLING-BRASS-WITH-UNION-&-BUSH-1/4"',
    materialGroup: "SM",
    qtyReq: "3",
    qtyApproved: "3",
    qtyIssued: "3",
    uom: "NOS",
    materialType: "ERSA",
    purpose: "OK",
    status: "Open",
    createdDate: "11/1/2024",
    approvalDate: "11/1/2024",
    createdBy: "snehal",
    approvedBy: "himanshu",
  },
  {
    reqId: "MR2500008",
    srNo: "10",
    materialCode: "60003443",
    description: "SM-MS-PIPE-10�",
    materialGroup: "SM",
    qtyReq: "4",
    qtyApproved: "4",
    qtyIssued: "4",
    uom: "M",
    materialType: "ERSA",
    purpose: "OK",
    status: "Open",
    createdDate: "11/2/2024",
    approvalDate: "11/2/2024",
    createdBy: "snehal",
    approvedBy: "himanshu",
  },
  {
    reqId: "MR2500008",
    srNo: "20",
    materialCode: "60003445",
    description: "SM-GI-COUPLING-6�",
    materialGroup: "SM",
    qtyReq: "3",
    qtyApproved: "3",
    qtyIssued: "3",
    uom: "NOS",
    materialType: "ERSA",
    purpose: "OK",
    status: "Open",
    createdDate: "11/4/2024",
    approvalDate: "11/4/2024",
    createdBy: "snehal",
    approvedBy: "himanshu",
  },
  {
    reqId: "MR2500008",
    srNo: "30",
    materialCode: "60003463",
    description: "SM-GUN-AIR-WG3020",
    materialGroup: "SM",
    qtyReq: "4",
    qtyApproved: "4",
    qtyIssued: "4",
    uom: "NOS",
    materialType: "ERSA",
    purpose: "OK",
    status: "Open",
    createdDate: "11/7/2024",
    approvalDate: "11/7/2024",
    createdBy: "snehal",
    approvedBy: "himanshu",
  },
  {
    reqId: "MR2500008",
    srNo: "40",
    materialCode: "60003465",
    description: "SM-HSS-TAPE-SET-1/4MM",
    materialGroup: "SM",
    qtyReq: "3",
    qtyApproved: "3",
    qtyIssued: "3",
    uom: "NOS",
    materialType: "ERSA",
    purpose: "OK",
    status: "Open",
    createdDate: "12/2/2024",
    approvalDate: "12/2/2024",
    createdBy: "snehal",
    approvedBy: "himanshu",
  },
  {
    reqId: "MR2500008",
    srNo: "50",
    materialCode: "60003474",
    description: 'SM-MS-HYDRAULIC-HEX-NIPPLE-3/8"X1/2"',
    materialGroup: "SM",
    qtyReq: "3",
    qtyApproved: "3",
    qtyIssued: "3",
    uom: "NOS",
    materialType: "ERSA",
    purpose: "OK",
    status: "Open",
    createdDate: "12/4/2024",
    approvalDate: "12/4/2024",
    createdBy: "snehal",
    approvedBy: "himanshu",
  },
  {
    reqId: "MR2500008",
    srNo: "60",
    materialCode: "60003487",
    description: "SM-COPPER-LUGSPIN-2.5MM",
    materialGroup: "SM",
    qtyReq: "4",
    qtyApproved: "4",
    qtyIssued: "4",
    uom: "NOS",
    materialType: "ERSA",
    purpose: "OK",
    status: "Open",
    createdDate: "12/8/2024",
    approvalDate: "12/8/2024",
    createdBy: "snehal",
    approvedBy: "himanshu",
  },
  {
    reqId: "MR2500008",
    srNo: "70",
    materialCode: "60003506",
    description: "SM-SS316-WELDING-ROD-3.15",
    materialGroup: "SM",
    qtyReq: "4",
    qtyApproved: "4",
    qtyIssued: "4",
    uom: "PAC",
    materialType: "ERSA",
    purpose: "OK",
    status: "Open",
    createdDate: "12/10/2024",
    approvalDate: "12/10/2024",
    createdBy: "snehal",
    approvedBy: "himanshu",
  },
  {
    reqId: "MR2500008",
    srNo: "80",
    materialCode: "60003507",
    description: "SM-PAINT-APCOLITE-RED-PO-0518",
    materialGroup: "SM",
    qtyReq: "3",
    qtyApproved: "3",
    qtyIssued: "3",
    uom: "L",
    materialType: "ERSA",
    purpose: "OK",
    status: "Partially Open",
    createdDate: "12/11/2024",
    approvalDate: "12/11/2024",
    createdBy: "snehal",
    approvedBy: "himanshu",
  },
  {
    reqId: "MR2500008",
    srNo: "90",
    materialCode: "60003512",
    description: 'SM-PVC-CONNECTOR-1"X1"',
    materialGroup: "SM",
    qtyReq: "2",
    qtyApproved: "2",
    qtyIssued: "2",
    uom: "NOS",
    materialType: "ERSA",
    purpose: "OK",
    status: "Partially Open",
    createdDate: "1/2/2024",
    approvalDate: "1/2/2024",
    createdBy: "snehal",
    approvedBy: "himanshu",
  },
  {
    reqId: "MR2500008",
    srNo: "100",
    materialCode: "60003520",
    description: "SM-SILICON-ANABOND-RTV",
    materialGroup: "SM",
    qtyReq: "4",
    qtyApproved: "4",
    qtyIssued: "4",
    uom: "NOS",
    materialType: "ERSA",
    purpose: "OK",
    status: "Partially Open",
    createdDate: "1/7/2024",
    approvalDate: "1/7/2024",
    createdBy: "snehal",
    approvedBy: "himanshu",
  },
  {
    reqId: "MR2500008",
    srNo: "110",
    materialCode: "60003524",
    description: "SM-FILE-HALF-ROUND-12''",
    materialGroup: "SM",
    qtyReq: "5",
    qtyApproved: "5",
    qtyIssued: "5",
    uom: "NOS",
    materialType: "ERSA",
    purpose: "OK",
    status: "Partially Open",
    createdDate: "10/1/2023",
    approvalDate: "10/1/2023",
    createdBy: "snehal",
    approvedBy: "himanshu",
  },
  {
    reqId: "MR2500008",
    srNo: "120",
    materialCode: "60003537",
    description: "SM-PAINT-APCOLITE-GREY-AD",
    materialGroup: "SM",
    qtyReq: "2",
    qtyApproved: "2",
    qtyIssued: "2",
    uom: "L",
    materialType: "ERSA",
    purpose: "OK",
    status: "Partially Open",
    createdDate: "10/1/2023",
    approvalDate: "10/1/2023",
    createdBy: "snehal",
    approvedBy: "himanshu",
  },
  {
    reqId: "MR2500009",
    srNo: "10",
    materialCode: "60003542",
    description: 'SM-PU-TROLLEY-WHEEL-3" MOVABLE-BRACKET',
    materialGroup: "SM",
    qtyReq: "5",
    qtyApproved: "5",
    qtyIssued: "5",
    uom: "NOS",
    materialType: "ERSA",
    purpose: "OK",
    status: "Partially Open",
    createdDate: "10/1/2023",
    approvalDate: "10/1/2023",
    createdBy: "snehal",
    approvedBy: "himanshu",
  },
  {
    reqId: "MR2500009",
    srNo: "20",
    materialCode: "60003555",
    description: "SM-GI-PATTI-25X3MM",
    materialGroup: "SM",
    qtyReq: "6",
    qtyApproved: "6",
    qtyIssued: "6",
    uom: "KG",
    materialType: "ERSA",
    purpose: "OK",
    status: "Partially Open",
    createdDate: "10/1/2023",
    approvalDate: "10/1/2023",
    createdBy: "snehal",
    approvedBy: "himanshu",
  },
  {
    reqId: "MR2500009",
    srNo: "30",
    materialCode: "60003600",
    description: "SM-HYDRAULIC-SEAL-KIT-63X510MM",
    materialGroup: "SM",
    qtyReq: "63",
    qtyApproved: "63",
    qtyIssued: "63",
    uom: "NOS",
    materialType: "ERSA",
    purpose: "OK",
    status: "Partially Open",
    createdDate: "10/1/2023",
    approvalDate: "10/1/2023",
    createdBy: "snehal",
    approvedBy: "himanshu",
  },
  {
    reqId: "MR2500009",
    srNo: "40",
    materialCode: "60003626",
    description: "SM-INSTALL-TILT-LOCK-VALVE-MH-02049427",
    materialGroup: "SM",
    qtyReq: "3",
    qtyApproved: "3",
    qtyIssued: "3",
    uom: "NOS",
    materialType: "ERSA",
    purpose: "OK",
    status: "Partially Open",
    createdDate: "10/1/2023",
    approvalDate: "10/1/2023",
    createdBy: "snehal",
    approvedBy: "himanshu",
  },
  {
    reqId: "MR2500009",
    srNo: "50",
    materialCode: "60003634",
    description: "SM-N8-SHAFT-30X510-WITH-HARD-CHROME",
    materialGroup: "SM",
    qtyReq: "34",
    qtyApproved: "34",
    qtyIssued: "34",
    uom: "NOS",
    materialType: "ERSA",
    purpose: "OK",
    status: "Partially Open",
    createdDate: "10/1/2023",
    approvalDate: "10/1/2023",
    createdBy: "snehal",
    approvedBy: "himanshu",
  },
  {
    reqId: "MR2500009",
    srNo: "60",
    materialCode: "60003636",
    description: "SM-SS-SCREW-8X32MM",
    materialGroup: "SM",
    qtyReq: "56",
    qtyApproved: "56",
    qtyIssued: "56",
    uom: "NOS",
    materialType: "ERSA",
    purpose: "OK",
    status: "Partially Open",
    createdDate: "10/1/2023",
    approvalDate: "10/1/2023",
    createdBy: "snehal",
    approvedBy: "himanshu",
  },
  {
    reqId: "MR2500009",
    srNo: "70",
    materialCode: "60003650",
    description: "SM-LOCK-NUT-M10",
    materialGroup: "SM",
    qtyReq: "3",
    qtyApproved: "3",
    qtyIssued: "3",
    uom: "NOS",
    materialType: "ERSA",
    purpose: "OK",
    status: "Partially Open",
    createdDate: "10/1/2023",
    approvalDate: "10/1/2023",
    createdBy: "snehal",
    approvedBy: "himanshu",
  },
  {
    reqId: "MR2500009",
    srNo: "80",
    materialCode: "60003659",
    description: "SM-NYLON-PIPE-4MM",
    materialGroup: "SM",
    qtyReq: "5",
    qtyApproved: "5",
    qtyIssued: "5",
    uom: "M",
    materialType: "ERSA",
    purpose: "OK",
    status: "Partially Open",
    createdDate: "10/1/2023",
    approvalDate: "10/1/2023",
    createdBy: "snehal",
    approvedBy: "himanshu",
  },
  {
    reqId: "MR2500009",
    srNo: "90",
    materialCode: "60003668",
    description: 'SM-BRASS-VALVE-BALL-1/4"',
    materialGroup: "SM",
    qtyReq: "5",
    qtyApproved: "5",
    qtyIssued: "5",
    uom: "NOS",
    materialType: "ERSA",
    purpose: "OK",
    status: "Partially Open",
    createdDate: "10/1/2023",
    approvalDate: "10/1/2023",
    createdBy: "snehal",
    approvedBy: "himanshu",
  },
  {
    reqId: "MR2500009",
    srNo: "100",
    materialCode: "60003670",
    description: 'SM-MS-NIPPLE-1/4"-C-CLASS',
    materialGroup: "SM",
    qtyReq: "6",
    qtyApproved: "6",
    qtyIssued: "6",
    uom: "NOS",
    materialType: "ERSA",
    purpose: "OK",
    status: "Partially Open",
    createdDate: "10/1/2023",
    approvalDate: "10/1/2023",
    createdBy: "snehal",
    approvedBy: "himanshu",
  },
  {
    reqId: "MR2500009",
    srNo: "110",
    materialCode: "60003688",
    description: "SM-PAINT-WATER-PRIMER",
    materialGroup: "SM",
    qtyReq: "6",
    qtyApproved: "6",
    qtyIssued: "6",
    uom: "L",
    materialType: "ERSA",
    purpose: "OK",
    status: "Partially Open",
    createdDate: "10/1/2023",
    approvalDate: "10/1/2023",
    createdBy: "snehal",
    approvedBy: "himanshu",
  },
  {
    reqId: "MR2500009",
    srNo: "120",
    materialCode: "60003690",
    description: "SM-VACCUM-PAD-300MM",
    materialGroup: "SM",
    qtyReq: "7",
    qtyApproved: "7",
    qtyIssued: "7",
    uom: "NOS",
    materialType: "ERSA",
    purpose: "OK",
    status: "Partially Open",
    createdDate: "10/1/2023",
    approvalDate: "10/1/2023",
    createdBy: "snehal",
    approvedBy: "himanshu",
  },
  {
    reqId: "MR2500009",
    srNo: "130",
    materialCode: "60003710",
    description: 'SM-MS-COUPLING-1/4"',
    materialGroup: "SM",
    qtyReq: "8",
    qtyApproved: "8",
    qtyIssued: "8",
    uom: "NOS",
    materialType: "ERSA",
    purpose: "OK",
    status: "Partially Open",
    createdDate: "10/1/2023",
    approvalDate: "10/1/2023",
    createdBy: "snehal",
    approvedBy: "himanshu",
  },
  {
    reqId: "MR2500009",
    srNo: "140",
    materialCode: "60003711",
    description: 'SM-MS-COUPLING-3/8"',
    materialGroup: "SM",
    qtyReq: "6",
    qtyApproved: "6",
    qtyIssued: "6",
    uom: "NOS",
    materialType: "ERSA",
    purpose: "OK",
    status: "Closed",
    createdDate: "10/1/2023",
    approvalDate: "10/1/2023",
    createdBy: "snehal",
    approvedBy: "himanshu",
  },
  {
    reqId: "MR2500009",
    srNo: "150",
    materialCode: "60003720",
    description: "SM-NEOPERENE-OIL-SEAL-70X90X13",
    materialGroup: "SM",
    qtyReq: "2",
    qtyApproved: "2",
    qtyIssued: "2",
    uom: "NOS",
    materialType: "ERSA",
    purpose: "OK",
    status: "Closed",
    createdDate: "10/1/2023",
    approvalDate: "10/1/2023",
    createdBy: "snehal",
    approvedBy: "himanshu",
  },
  {
    reqId: "MR2500009",
    srNo: "160",
    materialCode: "60003726",
    description: 'SM-BRASS-HEX-NIPPLE-3/8"',
    materialGroup: "SM",
    qtyReq: "56",
    qtyApproved: "56",
    qtyIssued: "56",
    uom: "NOS",
    materialType: "ERSA",
    purpose: "OK",
    status: "Closed",
    createdDate: "10/1/2023",
    approvalDate: "10/1/2023",
    createdBy: "snehal",
    approvedBy: "himanshu",
  },
  {
    reqId: "MR2500010",
    srNo: "10",
    materialCode: "60003727",
    description: 'SM-BRASS-VALVE-BALL-3/8"',
    materialGroup: "SM",
    qtyReq: "5",
    qtyApproved: "5",
    qtyIssued: "5",
    uom: "NOS",
    materialType: "ERSA",
    purpose: "OK",
    status: "Closed",
    createdDate: "10/1/2023",
    approvalDate: "10/1/2023",
    createdBy: "snehal",
    approvedBy: "himanshu",
  },
  {
    reqId: "MR2500010",
    srNo: "20",
    materialCode: "60003730",
    description: "SM-MS-CIRCLIP-EXTERNAL-18MM",
    materialGroup: "SM",
    qtyReq: "5",
    qtyApproved: "5",
    qtyIssued: "5",
    uom: "NOS",
    materialType: "ERSA",
    purpose: "OK",
    status: "Closed",
    createdDate: "10/1/2023",
    approvalDate: "10/1/2023",
    createdBy: "snehal",
    approvedBy: "himanshu",
  },
  {
    reqId: "MR2500010",
    srNo: "30",
    materialCode: "60003755",
    description: 'SM-PVC-PIPE-BRAIDED-1"',
    materialGroup: "SM",
    qtyReq: "5",
    qtyApproved: "5",
    qtyIssued: "5",
    uom: "M",
    materialType: "ERSA",
    purpose: "OK",
    status: "Closed",
    createdDate: "10/1/2024",
    approvalDate: "10/1/2024",
    createdBy: "snehal",
    approvedBy: "himanshu",
  },
  {
    reqId: "MR2500010",
    srNo: "40",
    materialCode: "60003767",
    description: 'SM-BRASS-BIB-COCK-LOCKING-1/2"',
    materialGroup: "SM",
    qtyReq: "6",
    qtyApproved: "6",
    qtyIssued: "6",
    uom: "NOS",
    materialType: "ERSA",
    purpose: "OK",
    status: "Closed",
    createdDate: "10/1/2024",
    approvalDate: "10/1/2024",
    createdBy: "snehal",
    approvedBy: "himanshu",
  },
  {
    reqId: "MR2500010",
    srNo: "50",
    materialCode: "60003784",
    description: "SM-PUMP-AIR-COOLER",
    materialGroup: "SM",
    qtyReq: "6",
    qtyApproved: "6",
    qtyIssued: "6",
    uom: "NOS",
    materialType: "ERSA",
    purpose: "OK",
    status: "Closed",
    createdDate: "10/1/2024",
    approvalDate: "10/1/2024",
    createdBy: "snehal",
    approvedBy: "himanshu",
  },
  {
    reqId: "MR2500010",
    srNo: "60",
    materialCode: "60003794",
    description: "SM-SS-SCREW-6X25MM",
    materialGroup: "SM",
    qtyReq: "6",
    qtyApproved: "6",
    qtyIssued: "6",
    uom: "NOS",
    materialType: "ERSA",
    purpose: "OK",
    status: "Closed",
    createdDate: "10/1/2024",
    approvalDate: "10/1/2024",
    createdBy: "snehal",
    approvedBy: "himanshu",
  },
  {
    reqId: "MR2500010",
    srNo: "70",
    materialCode: "60003799",
    description: 'SM-MS-CHAIN-SPROCKET-DUPLEX-1"-13TEETH',
    materialGroup: "SM",
    qtyReq: "6",
    qtyApproved: "6",
    qtyIssued: "6",
    uom: "NOS",
    materialType: "ERSA",
    purpose: "OK",
    status: "Partially Open",
    createdDate: "10/1/2024",
    approvalDate: "10/1/2024",
    createdBy: "snehal",
    approvedBy: "himanshu",
  },
  {
    reqId: "MR2500010",
    srNo: "80",
    materialCode: "60003806",
    description: "SM-GI-SHEET-1MM",
    materialGroup: "SM",
    qtyReq: "67",
    qtyApproved: "67",
    qtyIssued: "67",
    uom: "KG",
    materialType: "ERSA",
    purpose: "OK",
    status: "Partially Open",
    createdDate: "10/1/2024",
    approvalDate: "10/1/2024",
    createdBy: "snehal",
    approvedBy: "himanshu",
  },
  {
    reqId: "MR2500010",
    srNo: "90",
    materialCode: "60003810",
    description: "SM-SILICON-CORD-5MM-RED",
    materialGroup: "SM",
    qtyReq: "67",
    qtyApproved: "67",
    qtyIssued: "67",
    uom: "M",
    materialType: "ERSA",
    purpose: "OK",
    status: "Partially Open",
    createdDate: "10/1/2024",
    approvalDate: "10/1/2024",
    createdBy: "snehal",
    approvedBy: "himanshu",
  },
  {
    reqId: "MR2500010",
    srNo: "100",
    materialCode: "60003815",
    description: 'SM-HYDRAULIC-PIPE-3/8"X950MM-WITH-FITTIN',
    materialGroup: "SM",
    qtyReq: "67",
    qtyApproved: "67",
    qtyIssued: "67",
    uom: "NOS",
    materialType: "ERSA",
    purpose: "OK",
    status: "Partially Open",
    createdDate: "10/1/2024",
    approvalDate: "10/1/2024",
    createdBy: "snehal",
    approvedBy: "himanshu",
  },
  {
    reqId: "MR2500010",
    srNo: "110",
    materialCode: "60003823",
    description: "SM-MS-BOX-PIPE-100X100X6MM",
    materialGroup: "SM",
    qtyReq: "67",
    qtyApproved: "67",
    qtyIssued: "67",
    uom: "KG",
    materialType: "ERSA",
    purpose: "OK",
    status: "Partially Open",
    createdDate: "11/1/2024",
    approvalDate: "11/1/2024",
    createdBy: "snehal",
    approvedBy: "himanshu",
  },
  {
    reqId: "MR2500010",
    srNo: "120",
    materialCode: "60003849",
    description: "SM-CARBIDE-DRILL-5MM",
    materialGroup: "SM",
    qtyReq: "8",
    qtyApproved: "8",
    qtyIssued: "8",
    uom: "NOS",
    materialType: "ERSA",
    purpose: "OK",
    status: "Partially Open",
    createdDate: "11/2/2024",
    approvalDate: "11/2/2024",
    createdBy: "snehal",
    approvedBy: "himanshu",
  },
  {
    reqId: "MR2500010",
    srNo: "130",
    materialCode: "60003859",
    description: "SM-PU-UNION-8X8MM",
    materialGroup: "SM",
    qtyReq: "6",
    qtyApproved: "6",
    qtyIssued: "6",
    uom: "NOS",
    materialType: "ERSA",
    purpose: "OK",
    status: "Partially Open",
    createdDate: "11/4/2024",
    approvalDate: "11/4/2024",
    createdBy: "snehal",
    approvedBy: "himanshu",
  },
  {
    reqId: "MR2500010",
    srNo: "140",
    materialCode: "60003860",
    description: 'SM-SS-VALVE-BALL-1�"',
    materialGroup: "SM",
    qtyReq: "5",
    qtyApproved: "5",
    qtyIssued: "5",
    uom: "NOS",
    materialType: "ERSA",
    purpose: "OK",
    status: "Partially Open",
    createdDate: "11/7/2024",
    approvalDate: "11/7/2024",
    createdBy: "snehal",
    approvedBy: "himanshu",
  },
  {
    reqId: "MR2500011",
    srNo: "10",
    materialCode: "60003861",
    description: "SM-ALLEN-BOLT-20X90MM",
    materialGroup: "SM",
    qtyReq: "4",
    qtyApproved: "4",
    qtyIssued: "4",
    uom: "NOS",
    materialType: "ERSA",
    purpose: "OK",
    status: "Partially Open",
    createdDate: "12/2/2024",
    approvalDate: "12/2/2024",
    createdBy: "snehal",
    approvedBy: "himanshu",
  },
  {
    reqId: "MR2500011",
    srNo: "20",
    materialCode: "60003866",
    description: "SM-EN9-BRIGHT-ROUND-BAR-50MM",
    materialGroup: "SM",
    qtyReq: "3",
    qtyApproved: "3",
    qtyIssued: "3",
    uom: "KG",
    materialType: "ERSA",
    purpose: "OK",
    status: "Partially Open",
    createdDate: "12/4/2024",
    approvalDate: "12/4/2024",
    createdBy: "snehal",
    approvedBy: "himanshu",
  },
  {
    reqId: "MR2500011",
    srNo: "30",
    materialCode: "60003867",
    description: 'SM-TROLLY-WHEEL-12"-WITH-BEARING',
    materialGroup: "SM",
    qtyReq: "3",
    qtyApproved: "3",
    qtyIssued: "3",
    uom: "NOS",
    materialType: "ERSA",
    purpose: "OK",
    status: "Partially Open",
    createdDate: "12/8/2024",
    approvalDate: "12/8/2024",
    createdBy: "snehal",
    approvedBy: "himanshu",
  },
  {
    reqId: "MR2500011",
    srNo: "40",
    materialCode: "60003924",
    description: 'SM-BEARING-PULLER-10"-3LEG',
    materialGroup: "SM",
    qtyReq: "5",
    qtyApproved: "5",
    qtyIssued: "5",
    uom: "NOS",
    materialType: "ERSA",
    purpose: "OK",
    status: "Partially Open",
    createdDate: "12/10/2024",
    approvalDate: "12/10/2024",
    createdBy: "snehal",
    approvedBy: "himanshu",
  },
  {
    reqId: "MR2500011",
    srNo: "50",
    materialCode: "60003945",
    description: "SM-MS-CLUTCH-PLATE-250X75MM",
    materialGroup: "SM",
    qtyReq: "7",
    qtyApproved: "7",
    qtyIssued: "7",
    uom: "NOS",
    materialType: "ERSA",
    purpose: "OK",
    status: "Partially Open",
    createdDate: "12/11/2024",
    approvalDate: "12/11/2024",
    createdBy: "snehal",
    approvedBy: "himanshu",
  },
  {
    reqId: "MR2500011",
    srNo: "60",
    materialCode: "60003954",
    description: "SM-ALU-LUGS-RING-25SQMM",
    materialGroup: "SM",
    qtyReq: "7",
    qtyApproved: "7",
    qtyIssued: "7",
    uom: "NOS",
    materialType: "ERSA",
    purpose: "OK",
    status: "Partially Open",
    createdDate: "1/2/2024",
    approvalDate: "1/2/2024",
    createdBy: "snehal",
    approvedBy: "himanshu",
  },
  {
    reqId: "MR2500011",
    srNo: "70",
    materialCode: "60003957",
    description: "SM-PEDAL-MH02420594",
    materialGroup: "SM",
    qtyReq: "7",
    qtyApproved: "7",
    qtyIssued: "7",
    uom: "NOS",
    materialType: "ERSA",
    purpose: "OK",
    status: "Closed",
    createdDate: "1/7/2024",
    approvalDate: "1/7/2024",
    createdBy: "snehal",
    approvedBy: "himanshu",
  },
  {
    reqId: "MR2500011",
    srNo: "80",
    materialCode: "60003962",
    description: "SM-HYDRAULIC-SEAL-KIT-80MM",
    materialGroup: "SM",
    qtyReq: "7",
    qtyApproved: "7",
    qtyIssued: "7",
    uom: "NOS",
    materialType: "ERSA",
    purpose: "OK",
    status: "Closed",
    createdDate: "10/1/2023",
    approvalDate: "10/1/2023",
    createdBy: "snehal",
    approvedBy: "himanshu",
  },
  {
    reqId: "MR2500011",
    srNo: "90",
    materialCode: "60003993",
    description: "SM-HSS-DRILL-BIT-TAPER-SHUNK-18MM-IT",
    materialGroup: "SM",
    qtyReq: "7",
    qtyApproved: "7",
    qtyIssued: "7",
    uom: "NOS",
    materialType: "ERSA",
    purpose: "OK",
    status: "Closed",
    createdDate: "10/1/2023",
    approvalDate: "10/1/2023",
    createdBy: "snehal",
    approvedBy: "himanshu",
  },
  {
    reqId: "MR2500011",
    srNo: "100",
    materialCode: "60003998",
    description: 'SM-DAIMOND-CUP-WHEEL-4"',
    materialGroup: "SM",
    qtyReq: "7",
    qtyApproved: "7",
    qtyIssued: "7",
    uom: "NOS",
    materialType: "ERSA",
    purpose: "OK",
    status: "Closed",
    createdDate: "10/1/2023",
    approvalDate: "10/1/2023",
    createdBy: "snehal",
    approvedBy: "himanshu",
  },
  {
    reqId: "MR2500011",
    srNo: "110",
    materialCode: "60004001",
    description: "EE-CONTACTOR-POWER-LC1F185,3P-185A",
    materialGroup: "SM",
    qtyReq: "7",
    qtyApproved: "7",
    qtyIssued: "7",
    uom: "NOS",
    materialType: "ERSA",
    purpose: "OK",
    status: "Closed",
    createdDate: "10/1/2023",
    approvalDate: "10/1/2023",
    createdBy: "snehal",
    approvedBy: "himanshu",
  },
  {
    reqId: "MR2500011",
    srNo: "120",
    materialCode: "60004019",
    description: "EE-LAMP-LED-0.5W",
    materialGroup: "SM",
    qtyReq: "7",
    qtyApproved: "7",
    qtyIssued: "7",
    uom: "NOS",
    materialType: "ERSA",
    purpose: "OK",
    status: "Closed",
    createdDate: "10/1/2023",
    approvalDate: "10/1/2023",
    createdBy: "snehal",
    approvedBy: "himanshu",
  },
  {
    reqId: "MR2500011",
    srNo: "130",
    materialCode: "60004023",
    description: "EE-PVC-CASSING-PATTY-25X32",
    materialGroup: "SM",
    qtyReq: "7",
    qtyApproved: "7",
    qtyIssued: "7",
    uom: "NOS",
    materialType: "ERSA",
    purpose: "OK",
    status: "Closed",
    createdDate: "10/1/2023",
    approvalDate: "10/1/2023",
    createdBy: "snehal",
    approvedBy: "himanshu",
  },
  {
    reqId: "MR2500011",
    srNo: "140",
    materialCode: "60004040",
    description: "SM-VALVE-RELFE-MTC-02W",
    materialGroup: "SM",
    qtyReq: "7",
    qtyApproved: "7",
    qtyIssued: "7",
    uom: "NOS",
    materialType: "ERSA",
    purpose: "OK",
    status: "Closed",
    createdDate: "10/1/2023",
    approvalDate: "10/1/2023",
    createdBy: "snehal",
    approvedBy: "himanshu",
  },
  {
    reqId: "MR2500012",
    srNo: "10",
    materialCode: "60004042",
    description: "SM-BEARING-22316-EW33J-ZKL",
    materialGroup: "SM",
    qtyReq: "7",
    qtyApproved: "7",
    qtyIssued: "7",
    uom: "NOS",
    materialType: "ERSA",
    purpose: "OK",
    status: "Closed",
    createdDate: "10/1/2023",
    approvalDate: "10/1/2023",
    createdBy: "snehal",
    approvedBy: "himanshu",
  },
  {
    reqId: "MR2500012",
    srNo: "20",
    materialCode: "60004046",
    description: "SM-BRAKE-LINER-MODEL-NO-2-EOT",
    materialGroup: "SM",
    qtyReq: "654",
    qtyApproved: "654",
    qtyIssued: "654",
    uom: "NOS",
    materialType: "ERSA",
    purpose: "OK",
    status: "Partially Open",
    createdDate: "10/1/2023",
    approvalDate: "10/1/2023",
    createdBy: "snehal",
    approvedBy: "himanshu",
  },
  {
    reqId: "MR2500012",
    srNo: "30",
    materialCode: "60004047",
    description: "SM-MS-SHAFT-20X1600MM",
    materialGroup: "SM",
    qtyReq: "3",
    qtyApproved: "3",
    qtyIssued: "3",
    uom: "NOS",
    materialType: "ERSA",
    purpose: "OK",
    status: "Partially Open",
    createdDate: "10/1/2023",
    approvalDate: "10/1/2023",
    createdBy: "snehal",
    approvedBy: "himanshu",
  },
  {
    reqId: "MR2500012",
    srNo: "40",
    materialCode: "60004077",
    description: "SM-SPRING-MH02171386",
    materialGroup: "SM",
    qtyReq: "4",
    qtyApproved: "4",
    qtyIssued: "4",
    uom: "NOS",
    materialType: "ERSA",
    purpose: "OK",
    status: "Partially Open",
    createdDate: "10/1/2023",
    approvalDate: "10/1/2023",
    createdBy: "snehal",
    approvedBy: "himanshu",
  },
  {
    reqId: "MR2500012",
    srNo: "50",
    materialCode: "60004099",
    description: "SM-MS-CHECK-NUT-65X45MM",
    materialGroup: "SM",
    qtyReq: "56",
    qtyApproved: "56",
    qtyIssued: "56",
    uom: "NOS",
    materialType: "ERSA",
    purpose: "OK",
    status: "Partially Open",
    createdDate: "10/1/2023",
    approvalDate: "10/1/2023",
    createdBy: "snehal",
    approvedBy: "himanshu",
  },
  {
    reqId: "MR2500012",
    srNo: "60",
    materialCode: "60004110",
    description: "SM-HAMMER-DRILL-BIT-20MM",
    materialGroup: "SM",
    qtyReq: "6",
    qtyApproved: "6",
    qtyIssued: "6",
    uom: "NOS",
    materialType: "ERSA",
    purpose: "OK",
    status: "Partially Open",
    createdDate: "10/1/2023",
    approvalDate: "10/1/2023",
    createdBy: "snehal",
    approvedBy: "himanshu",
  },
  {
    reqId: "MR2500012",
    srNo: "70",
    materialCode: "60004117",
    description: "SM-PVC-PIPE-1��",
    materialGroup: "SM",
    qtyReq: "54",
    qtyApproved: "54",
    qtyIssued: "54",
    uom: "M",
    materialType: "ERSA",
    purpose: "OK",
    status: "Partially Open",
    createdDate: "10/1/2023",
    approvalDate: "10/1/2023",
    createdBy: "snehal",
    approvedBy: "himanshu",
  },
  {
    reqId: "MR2500012",
    srNo: "80",
    materialCode: "60004119",
    description: "SM-WIRE-ROPE-16MM",
    materialGroup: "SM",
    qtyReq: "45",
    qtyApproved: "45",
    qtyIssued: "45",
    uom: "M",
    materialType: "ERSA",
    purpose: "OK",
    status: "Partially Open",
    createdDate: "10/1/2023",
    approvalDate: "10/1/2023",
    createdBy: "snehal",
    approvedBy: "himanshu",
  },
  {
    reqId: "MR2500013",
    srNo: "10",
    materialCode: "60004184",
    description: "SM-PUMP-0.37KW-0.5HP-2880RPM",
    materialGroup: "SM",
    qtyReq: "6",
    qtyApproved: "6",
    qtyIssued: "6",
    uom: "NOS",
    materialType: "ERSA",
    purpose: "OK",
    status: "Partially Open",
    createdDate: "10/1/2023",
    approvalDate: "10/1/2023",
    createdBy: "snehal",
    approvedBy: "himanshu",
  },
  {
    reqId: "MR2500013",
    srNo: "20",
    materialCode: "60004215",
    description: 'SM-RUBBER-BLACK-HOSE-PIPE-1"',
    materialGroup: "SM",
    qtyReq: "543",
    qtyApproved: "543",
    qtyIssued: "543",
    uom: "M",
    materialType: "ERSA",
    purpose: "OK",
    status: "Partially Open",
    createdDate: "10/1/2023",
    approvalDate: "10/1/2023",
    createdBy: "snehal",
    approvedBy: "himanshu",
  },
  {
    reqId: "MR2500013",
    srNo: "30",
    materialCode: "60004226",
    description: 'SM-SS-CLAMP-HOSE-1�"',
    materialGroup: "SM",
    qtyReq: "4",
    qtyApproved: "4",
    qtyIssued: "4",
    uom: "NOS",
    materialType: "ERSA",
    purpose: "OK",
    status: "Partially Open",
    createdDate: "10/1/2023",
    approvalDate: "10/1/2023",
    createdBy: "snehal",
    approvedBy: "himanshu",
  },
  {
    reqId: "MR2500013",
    srNo: "40",
    materialCode: "60004248",
    description: 'SM-SS-SCREW-1"',
    materialGroup: "SM",
    qtyReq: "56",
    qtyApproved: "56",
    qtyIssued: "56",
    uom: "NOS",
    materialType: "ERSA",
    purpose: "OK",
    status: "Partially Open",
    createdDate: "10/1/2023",
    approvalDate: "10/1/2023",
    createdBy: "snehal",
    approvedBy: "himanshu",
  },
  {
    reqId: "MR2500013",
    srNo: "50",
    materialCode: "60004258",
    description: "SM-SLEEVE-H-2332-WITH-LOCK-NUT",
    materialGroup: "SM",
    qtyReq: "54",
    qtyApproved: "54",
    qtyIssued: "54",
    uom: "NOS",
    materialType: "ERSA",
    purpose: "OK",
    status: "Partially Open",
    createdDate: "10/1/2023",
    approvalDate: "10/1/2023",
    createdBy: "snehal",
    approvedBy: "himanshu",
  },
  {
    reqId: "MR2500013",
    srNo: "60",
    materialCode: "60004259",
    description: "SM-NITRILE-RUBBER-OIL-SEAL-160X200X12",
    materialGroup: "SM",
    qtyReq: "3",
    qtyApproved: "3",
    qtyIssued: "3",
    uom: "NOS",
    materialType: "ERSA",
    purpose: "OK",
    status: "Partially Open",
    createdDate: "10/1/2024",
    approvalDate: "10/1/2024",
    createdBy: "snehal",
    approvedBy: "himanshu",
  },
  {
    reqId: "MR2500013",
    srNo: "70",
    materialCode: "60004270",
    description: "SM-GI-HEX-WASHER-10MM",
    materialGroup: "SM",
    qtyReq: "56",
    qtyApproved: "56",
    qtyIssued: "56",
    uom: "NOS",
    materialType: "ERSA",
    purpose: "OK",
    status: "Partially Open",
    createdDate: "10/1/2024",
    approvalDate: "10/1/2024",
    createdBy: "snehal",
    approvedBy: "himanshu",
  },
  {
    reqId: "MR2500013",
    srNo: "80",
    materialCode: "60004276",
    description: "SM-MS-BRIGHT-BAR-40MM",
    materialGroup: "SM",
    qtyReq: "5",
    qtyApproved: "5",
    qtyIssued: "5",
    uom: "KG",
    materialType: "ERSA",
    purpose: "OK",
    status: "Partially Open",
    createdDate: "10/1/2024",
    approvalDate: "10/1/2024",
    createdBy: "snehal",
    approvedBy: "himanshu",
  },
  {
    reqId: "MR2500013",
    srNo: "90",
    materialCode: "60004280",
    description: "SM-BUSH-MH97958145",
    materialGroup: "SM",
    qtyReq: "4",
    qtyApproved: "4",
    qtyIssued: "4",
    uom: "NOS",
    materialType: "ERSA",
    purpose: "OK",
    status: "Partially Open",
    createdDate: "10/1/2024",
    approvalDate: "10/1/2024",
    createdBy: "snehal",
    approvedBy: "himanshu",
  },
  {
    reqId: "MR2500013",
    srNo: "100",
    materialCode: "60004290",
    description: "SM-MINOR-SRV-KIT-MH40900296",
    materialGroup: "SM",
    qtyReq: "3",
    qtyApproved: "3",
    qtyIssued: "3",
    uom: "NOS",
    materialType: "ERSA",
    purpose: "OK",
    status: "Partially Open",
    createdDate: "10/1/2024",
    approvalDate: "10/1/2024",
    createdBy: "snehal",
    approvedBy: "himanshu",
  },
  {
    reqId: "MR2500013",
    srNo: "110",
    materialCode: "60004301",
    description: "SM-CONNECTOR-BRAKE-LINE-MH-02310194",
    materialGroup: "SM",
    qtyReq: "4",
    qtyApproved: "4",
    qtyIssued: "4",
    uom: "NOS",
    materialType: "ERSA",
    purpose: "OK",
    status: "Partially Open",
    createdDate: "10/1/2024",
    approvalDate: "10/1/2024",
    createdBy: "snehal",
    approvedBy: "himanshu",
  },
  {
    reqId: "MR2500013",
    srNo: "120",
    materialCode: "60004316",
    description: 'SM-PVC-TEE-1"',
    materialGroup: "SM",
    qtyReq: "5",
    qtyApproved: "5",
    qtyIssued: "5",
    uom: "NOS",
    materialType: "ERSA",
    purpose: "OK",
    status: "Partially Open",
    createdDate: "10/1/2024",
    approvalDate: "10/1/2024",
    createdBy: "snehal",
    approvedBy: "himanshu",
  },
  {
    reqId: "MR2500013",
    srNo: "130",
    materialCode: "60004317",
    description: 'SM-PVC-ELBOW-3/4"',
    materialGroup: "SM",
    qtyReq: "5",
    qtyApproved: "5",
    qtyIssued: "5",
    uom: "NOS",
    materialType: "ERSA",
    purpose: "OK",
    status: "Partially Open",
    createdDate: "10/1/2024",
    approvalDate: "10/1/2024",
    createdBy: "snehal",
    approvedBy: "himanshu",
  },
  {
    reqId: "MR2500013",
    srNo: "140",
    materialCode: "60004367",
    description: "SM-PAINT",
    materialGroup: "SM",
    qtyReq: "5",
    qtyApproved: "5",
    qtyIssued: "5",
    uom: "L",
    materialType: "ERSA",
    purpose: "OK",
    status: "Partially Open",
    createdDate: "11/1/2024",
    approvalDate: "11/1/2024",
    createdBy: "snehal",
    approvedBy: "himanshu",
  },
  {
    reqId: "MR2500013",
    srNo: "150",
    materialCode: "60004370",
    description: 'SM-MS-CLAMP-�"',
    materialGroup: "SM",
    qtyReq: "3",
    qtyApproved: "3",
    qtyIssued: "3",
    uom: "NOS",
    materialType: "ERSA",
    purpose: "OK",
    status: "Partially Open",
    createdDate: "11/2/2024",
    approvalDate: "11/2/2024",
    createdBy: "snehal",
    approvedBy: "himanshu",
  },
  {
    reqId: "MR2500013",
    srNo: "160",
    materialCode: "60004463",
    description: "SM-SS-WASHER-PLAIN-6MM",
    materialGroup: "SM",
    qtyReq: "5",
    qtyApproved: "5",
    qtyIssued: "5",
    uom: "NOS",
    materialType: "ERSA",
    purpose: "OK",
    status: "Partially Open",
    createdDate: "11/4/2024",
    approvalDate: "11/4/2024",
    createdBy: "snehal",
    approvedBy: "himanshu",
  },
];
